In [1]:
import nflpro

In [2]:
nflpro_api = nflpro.NFLProAPI()

## Stats

In [3]:
passing_stats = nflpro_api.get_passing_stats(
        limit=10,
        season=2025,
        season_type=None,
        week="WEEK_1",
)
if passing_stats:
        print("Passing Stats:")
        print(passing_stats)
        
nflpro_api.stats_to_dataframe(passing_stats)

Passing Stats:
{'limit': 10, 'season': 2025, 'week': 'WEEK_1', 'total': 33, 'passers': [{'cmp': 22, 'att': 30, 'yds': 244, 'td': 4, 'int': 0, 'rating': 136.66667, 'ypa': 8.13333, 'cmpPct': 0.73333, 'sack': 4, 'xCmp': 0.68423, 'cpoe': 0.0491, 'db': 34, 'epa': 7.06684, 'epaDb': 0.20785, 'avgTTT': 2.4344, 'avgTTP': 2.96667, 'avgTTS': 4.031, 'qbp': 9, 'qbpR': 0.26471, 'blitzR': 0.38235, 'drop': 1, 'dropR': 0.03333, 'ay': 62.21, 'yac': 182.09, 'xYac': 143.16852, 'yacPct': 0.74627, 'ayAtt': 4.25552, 'avgSep': 3.379, 'deepAttPct': 0, 'paDbPct': 0.35294, 'twAttPct': 0.2, 'nflId': '29851', 'weekSlug': 'WEEK_1', 'opponentTeamId': '3430', 'gameId': 2025090706, 'finalScore': '34-32', 'displayName': 'Aaron Rodgers', 'isHome': False, 'gameResult': 'W', 'positionGroup': 'QB', 'ngsPositionGroup': 'QB', 'fapiGameId': 'f591a382-311e-11f0-b670-ae1250fadad1', 'headshot': 'https://static.www.nfl.com/image/upload/{formatInstructions}/league/dypvakakxhccxs67tb0y', 'teamId': '3900', 'jerseyNumber': 8, 'position': 'QB', 'shortName': 'A.Rodgers', 'ngsPosition': 'QB', 'gp': 1, 'gs': 1, 'tg': 1, 'totalTg': 1, 'qp': True, 'cmpPG': 22, 'attPG': 30, 'ydsPG': 244, 'tdPG': 4, 'intPG': 0, 'sackPG': 4, 'dbPG': 34, 'epaPG': 7.06684, 'qbpPG': 9, 'dropPG': 1, 'twAttPG': 6}, {'cmp': 31, 'att': 45, 'yds': 290, 'td': 1, 'int': 2, 'rating': 75.23148, 'ypa': 6.44444, 'cmpPct': 0.68889, 'sack': 2, 'xCmp': 0.66567, 'cpoe': 0.02322, 'db': 48, 'epa': -5.22155, 'epaDb': -0.10878, 'avgTTT': 2.80387, 'avgTTP': 2.78235, 'avgTTS': 4.6025, 'qbp': 17, 'qbpR': 0.35417, 'blitzR': 0.04167, 'drop': 2, 'dropR': 0.04444, 'ay': 108.42, 'yac': 188.21, 'xYac': 156.74201, 'yacPct': 0.649, 'ayAtt': 5.15524, 'avgSep': 3.39966, 'deepAttPct': 0.02222, 'paDbPct': 0.27083, 'twAttPct': 0.04444, 'nflId': '33099', 'weekSlug': 'WEEK_1', 'opponentTeamId': '0920', 'gameId': 2025090701, 'finalScore': '16-17', 'displayName': 'Joe Flacco', 'isHome': True, 'gameResult': 'L', 'positionGroup': 'QB', 'ngsPositionGroup': 'QB', 'fapiGameId': 'f5919910-311e-11f0-b670-ae1250fadad1', 'headshot': 'https://static.www.nfl.com/image/upload/{formatInstructions}/league/vbqptn8emdlbeaz1kvmx', 'teamId': '1050', 'jerseyNumber': 15, 'position': 'QB', 'shortName': 'J.Flacco', 'ngsPosition': 'QB', 'gp': 1, 'gs': 1, 'tg': 1, 'totalTg': 1, 'qp': True, 'cmpPG': 31, 'attPG': 45, 'ydsPG': 290, 'tdPG': 1, 'intPG': 2, 'sackPG': 2, 'dbPG': 48, 'epaPG': -5.22155, 'qbpPG': 17, 'dropPG': 2, 'twAttPG': 2}, {'cmp': 21, 'att': 29, 'yds': 245, 'td': 1, 'int': 0, 'rating': 109.12356, 'ypa': 8.44828, 'cmpPct': 0.72414, 'sack': 3, 'xCmp': 0.65146, 'cpoe': 0.07268, 'db': 32, 'epa': 2.52034, 'epaDb': 0.07876, 'avgTTT': 2.4181, 'avgTTP': 2.42, 'avgTTS': 3.72067, 'qbp': 10, 'qbpR': 0.3125, 'blitzR': 0.28125, 'drop': 0, 'dropR': 0, 'ay': 167.72, 'yac': 87.94, 'xYac': 65.31333, 'yacPct': 0.35894, 'ayAtt': 7.78143, 'avgSep': 2.64845, 'deepAttPct': 0.06897, 'paDbPct': 0.34375, 'twAttPct': 0.10345, 'nflId': '34452', 'weekSlug': 'WEEK_1', 'opponentTeamId': '2120', 'gameId': 2025090711, 'finalScore': '14-9', 'displayName': 'Matthew Stafford', 'isHome': True, 'gameResult': 'W', 'positionGroup': 'QB', 'ngsPositionGroup': 'QB', 'fapiGameId': 'f61de743-311e-11f0-b670-ae1250fadad1', 'headshot': 'https://static.www.nfl.com/image/upload/{formatInstructions}/league/svxl2pk2cuqf26zrhii4', 'teamId': '2510', 'jerseyNumber': 9, 'position': 'QB', 'shortName': 'M.Stafford', 'ngsPosition': 'QB', 'gp': 1, 'gs': 1, 'tg': 1, 'totalTg': 1, 'qp': True, 'cmpPG': 21, 'attPG': 29, 'ydsPG': 245, 'tdPG': 1, 'intPG': 0, 'sackPG': 3, 'dbPG': 32, 'epaPG': 2.52034, 'qbpPG': 10, 'dropPG': 0, 'twAttPG': 3}, {'cmp': 17, 'att': 37, 'yds': 168, 'td': 0, 'int': 0, 'rating': 59.29054, 'ypa': 4.54054, 'cmpPct': 0.45946, 'sack': 2, 'xCmp': 0.5868, 'cpoe': -0.12734, 'db': 45, 'epa': -14.35467, 'epaDb': -0.31899, 'avgTTT': 2.68892, 'avgTTP': 2.68889, 'avgTTS': 4.5485, 'qbp': 22, 'qbpR': 0.48889, 'blitzR': 0.26667, 'drop': 3, 'dropR': 0.08108, 'ay': 72.05, 'yac': 95.95, 'xYac': 82.58188, 'yacPct': 0.57113, 'ayAtt': 5.74813, 'avgSep': 3.46041, 'deepAttPct': 0.02703, 'paDbPct': 0.2, 'twAttPct': 0.18919, 'nflId': '38605', 'weekSlug': 'WEEK_1', 'opponentTeamId': '5110', 'gameId': 2025090707, 'finalScore': '6-21', 'displayName': 'Russell Wilson', 'isHome': False, 'gameResult': 'L', 'positionGroup': 'QB', 'ngsPositionGroup': 'QB', 'fapiGameId': 'f591a57f-311e-11f0-b670-ae1250fadad1', 'headshot': 'https://static.www.nfl.com/image/upload/{formatInstructions}/league/vkstxj0evgkjiycu4glc', 'teamId': '3410', 'jerseyNumber': 3, 'position': 'QB', 'shortName': 'R.Wilson', 'ngsPosition': 'QB', 'gp': 1, 'gs': 1, 'tg': 1, 'totalTg': 1, 'qp': True, 'cmpPG': 17, 'attPG': 37, 'ydsPG': 168, 'tdPG': 0, 'intPG': 0, 'sackPG': 2, 'dbPG': 45, 'epaPG': -14.35467, 'qbpPG': 22, 'dropPG': 3, 'twAttPG': 7}, {'cmp': 24, 'att': 34, 'yds': 362, 'td': 1, 'int': 1, 'rating': 102.81863, 'ypa': 10.64706, 'cmpPct': 0.70588, 'sack': 4, 'xCmp': 0.6163, 'cpoe': 0.08958, 'db': 39, 'epa': 11.57749, 'epaDb': 0.29686, 'avgTTT': 2.78594, 'avgTTP': 2.58, 'avgTTS': 3.86775, 'qbp': 16, 'qbpR': 0.41026, 'blitzR': 0.4359, 'drop': 1, 'dropR': 0.02941, 'ay': 223.16, 'yac': 144.59, 'xYac': 114.98029, 'yacPct': 0.39942, 'ayAtt': 10.56121, 'avgSep': 3.18437, 'deepAttPct': 0.14706, 'paDbPct': 0.30769, 'twAttPct': 0.17647, 'nflId': '39987', 'weekSlug': 'WEEK_1', 'opponentTeamId': '3200', 'gameId': 2025090704, 'finalScore': '20-13', 'displayName': 'Geno Smith', 'isHome': False, 'gameResult': 'W', 'positionGroup': 'QB', 'ngsPositionGroup': 'QB', 'fapiGameId': 'f5919f8e-311e-11f0-b670-ae1250fadad1', 'headshot': 'https://static.www.nfl.com/image/upload/{formatInstructions}/league/tqy0933vz5yogwlefb1s', 'teamId': '2520', 'jerseyNumber': 7, 'position': 'QB', 'shortName': 'G.Smith', 'ngsPosition': 'QB', 'gp': 1, 'gs': 1, 'tg': 1, 'totalTg': 1, 'qp': True, 'cmpPG': 24, 'attPG': 34, 'ydsPG': 362, 'tdPG': 1, 'intPG': 1, 'sackPG': 4, 'dbPG': 39, 'epaPG': 11.57749, 'qbpPG': 16, 'dropPG': 1, 'twAttPG': 6}, {'cmp': 31, 'att': 39, 'yds': 225, 'td': 1, 'int': 1, 'rating': 88.56838, 'ypa': 5.76923, 'cmpPct': 0.79487, 'sack': 4, 'xCmp': 0.71199, 'cpoe': 0.08288, 'db': 43, 'epa': -0.90195, 'epaDb': -0.02098, 'avgTTT': 3.09079, 'avgTTP': 2.87273, 'avgTTS': 5.2655, 'qbp': 12, 'qbpR': 0.27907, 'blitzR': 0.11628, 'drop': 0, 'dropR': 0, 'ay': 100.98, 'yac': 128.14, 'xYac': 124.07268, 'yacPct': 0.56951, 'ayAtt': 4.45579, 'avgSep': 4.03764, 'deepAttPct': 0.05128, 'paDbPct': 0.23256, 'twAttPct': 0.15385, 'nflId': '43290', 'weekSlug': 'WEEK_1', 'opponentTeamId': '1800', 'gameId': 2025090710, 'finalScore': '13-27', 'displayName': 'Jared Goff', 'isHome': False, 'gameResult': 'L', 'positionGroup': 'QB', 'ngsPositionGroup': 'QB', 'fapiGameId': 'f61de295-311e-11f0-b670-ae1250fadad1', 'headshot': 'https://static.www.nfl.com/image/upload/{formatInstructions}/league/yggfwr4ak4po9byj0qor', 'teamId': '1540', 'jerseyNumber': 16, 'position': 'QB', 'shortName': 'J.Goff', 'ngsPosition': 'QB', 'gp': 1, 'gs': 1, 'tg': 1, 'totalTg': 1, 'qp': True, 'cmpPG': 31, 'attPG': 39, 'ydsPG': 225, 'tdPG': 1, 'intPG': 1, 'sackPG': 4, 'dbPG': 43, 'epaPG': -0.90195, 'qbpPG': 12, 'dropPG': 0, 'twAttPG': 6}, {'cmp': 21, 'att': 34, 'yds': 188, 'td': 0, 'int': 0, 'rating': 76.59314, 'ypa': 5.52941, 'cmpPct': 0.61765, 'sack': 0, 'xCmp': 0.57213, 'cpoe': 0.04551, 'db': 35, 'epa': -1.13336, 'epaDb': -0.03238, 'avgTTT': 2.95067, 'avgTTP': 2.7, 'avgTTS': 0, 'qbp': 12, 'qbpR': 0.34286, 'blitzR': 0.17143, 'drop': 3, 'dropR': 0.08824, 'ay': 112.2, 'yac': 75.8, 'xYac': 73.43314, 'yacPct': 0.40319, 'ayAtt': 10.18212, 'avgSep': 2.96985, 'deepAttPct': 0.17647, 'paDbPct': 0.2, 'twAttPct': 0.26471, 'nflId': '43424', 'weekSlug': 'WEEK_1', 'opponentTeamId': '3700', 'gameId': 2025090400, 'finalScore': '20-24', 'displayName': 'Dak Prescott', 'isHome': False, 'gameResult': 'L', 'positionGroup': 'QB', 'ngsPositionGroup': 'QB', 'fapiGameId': 'f5908b6d-311e-11f0-b670-ae1250fadad1', 'headshot': 'https://static.www.nfl.com/image/upload/{formatInstructions}/league/blixemm3s9sa4gmqk5yn', 'teamId': '1200', 'jerseyNumber': 4, 'position': 'QB', 'shortName': 'D.Prescott', 'ngsPosition': 'QB', 'gp': 1, 'gs': 1, 'tg': 1, 'totalTg': 1, 'qp': True, 'cmpPG': 21, 'attPG': 34, 'ydsPG': 188, 'tdPG': 0, 'intPG': 0, 'sackPG': 0, 'dbPG': 35, 'epaPG': -1.13336, 'qbpPG': 12, 'dropPG': 3, 'twAttPG': 9}, {'cmp': 24, 'att': 39, 'yds': 258, 'td': 1, 'int': 0, 'rating': 89.4765, 'ypa': 6.61538, 'cmpPct': 0.61538, 'sack': 2, 'xCmp': 0.69402, 'cpoe': -0.07863, 'db': 47, 'epa': 8.52113, 'epaDb': 0.1813, 'avgTTT': 2.3785, 'avgTTP': 2.51667, 'avgTTS': 5.7575, 'qbp': 12, 'qbpR': 0.25532, 'blitzR': 0.17021, 'drop': 2, 'dropR': 0.05128, 'ay': 133.52, 'yac': 124.48, 'xYac': 141.63409, 'yacPct': 0.48248, 'ayAtt': 6.95868, 'avgSep': 3.46216, 'deepAttPct': 0.10256, 'paDbPct': 0.2766, 'twAttPct': 0.05128, 'nflId': '44822', 'weekSlug': 'WEEK_1', 'opponentTeamId': '4400', 'gameId': 2025090500, 'finalScore': '21-27', 'displayName': 'Patrick Mahomes', 'isHome': False, 'gameResult': 'L', 'positionGroup': 'QB', 'ngsPositionGroup': 'QB', 'fapiGameId': 'f5919071-311e-11f0-b670-ae1250fadad1', 'headshot': 'https://static.www.nfl.com/image/upload/{formatInstructions}/league/iireqbn32cpg9fn4sfy7', 'teamId': '2310', 'jerseyNumber': 15, 'position': 'QB', 'shortName': 'P.Mahomes', 'ngsPosition': 'QB', 'gp': 1, 'gs': 1, 'tg': 1, 'totalTg': 1, 'qp': True, 'cmpPG': 24, 'attPG': 39, 'ydsPG': 258, 'tdPG': 1, 'intPG': 0, 'sackPG': 2, 'dbPG': 47, 'epaPG': 8.52113, 'qbpPG': 12, 'dropPG': 2, 'twAttPG': 2}, {'cmp': 17, 'att': 32, 'yds': 167, 'td': 3, 'int': 0, 'rating': 99.34896, 'ypa': 5.21875, 'cmpPct': 0.53125, 'sack': 1, 'xCmp': 0.56453, 'cpoe': -0.03328, 'db': 37, 'epa': 8.3865, 'epaDb': 0.22666, 'avgTTT': 2.94947, 'avgTTP': 2.575, 'avgTTS': 4.88, 'qbp': 15, 'qbpR': 0.40541, 'blitzR': 0.32432, 'drop': 0, 'dropR': 0, 'ay': 120.95, 'yac': 50.45, 'xYac': 87.56489, 'yacPct': 0.3021, 'ayAtt': 10.207, 'avgSep': 2.62485, 'deepAttPct': 0.15625, 'paDbPct': 0.21622, 'twAttPct': 0.1875, 'nflId': '46070', 'weekSlug': 'WEEK_1', 'opponentTeamId': '0200', 'gameId': 2025090700, 'finalScore': '23-20', 'displayName': 'Baker Mayfield', 'isHome': False, 'gameResult': 'W', 'positionGroup': 'QB', 'ngsPositionGroup': 'QB', 'fapiGameId': 'f5919639-311e-11f0-b670-ae1250fadad1', 'headshot': 'https://static.www.nfl.com/image/upload/{formatInstructions}/league/i2uufyghiphx4oihgucm', 'teamId': '4900', 'jerseyNumber': 6, 'position': 'QB', 'shortName': 'B.Mayfield', 'ngsPosition': 'QB', 'gp': 1, 'gs': 1, 'tg': 1, 'totalTg': 1, 'qp': True, 'cmpPG': 17, 'attPG': 32, 'ydsPG': 167, 'tdPG': 3, 'intPG': 0, 'sackPG': 1, 'dbPG': 37, 'epaPG': 8.3865, 'qbpPG': 15, 'dropPG': 0, 'twAttPG': 6}, {'cmp': 16, 'att': 23, 'yds': 150, 'td': 0, 'int': 0, 'rating': 87.22826, 'ypa': 6.52174, 'cmpPct': 0.69565, 'sack': 1, 'xCmp': 0.63289, 'cpoe': 0.06276, 'db': 25, 'epa': -11.58244, 'epaDb': -0.4633, 'avgTTT': 2.59459, 'avgTTP': 2.225, 'avgTTS': 2.577, 'qbp': 8, 'qbpR': 0.32, 'blitzR': 0.28, 'drop': 0, 'dropR': 0, 'ay': 97.33, 'yac': 56.52, 'xYac': 80.90801, 'yacPct': 0.3768, 'ayAtt': 8.29182, 'avgSep': 3.43634, 'deepAttPct': 0.08696, 'paDbPct': 0.08, 'twAttPct': 0.13043, 'nflId': '46072', 'weekSlug': 'WEEK_1', 'opponentTeamId': '4500', 'gameId': 2025090709, 'finalScore': '13-17', 'displayName': 'Sam Darnold', 'isHome': True, 'gameResult': 'L', 'positionGroup': 'QB', 'ngsPositionGroup': 'QB', 'fapiGameId': 'f61ddd60-311e-11f0-b670-ae1250fadad1', 'headshot': 'https://static.www.nfl.com/image/upload/{formatInstructions}/league/s5t8m6bhedjwwtfw3ild', 'teamId': '4600', 'jerseyNumber': 14, 'position': 'QB', 'shortName': 'S.Darnold', 'ngsPosition': 'QB', 'gp': 1, 'gs': 1, 'tg': 1, 'totalTg': 1, 'qp': True, 'cmpPG': 16, 'attPG': 23, 'ydsPG': 150, 'tdPG': 0, 'intPG': 0, 'sackPG': 1, 'dbPG': 25, 'epaPG': -11.58244, 'qbpPG': 8, 'dropPG': 0, 'twAttPG': 3}]}

,displayName,position,teamId,jerseyNumber,cmp,att,yds,td,int,rating,...,attPG,ydsPG,tdPG,intPG,sackPG,dbPG,epaPG,qbpPG,dropPG,twAttPG
0,Aaron Rodgers,QB,3900,8,22,30,244,4,0,136.66667,...,30,244,4,0,4,34,7.06684,9,1,6
1,Joe Flacco,QB,1050,15,31,45,290,1,2,75.23148,...,45,290,1,2,2,48,-5.22155,17,2,2
2,Matthew Stafford,QB,2510,9,21,29,245,1,0,109.12356,...,29,245,1,0,3,32,2.52034,10,0,3
3,Russell Wilson,QB,3410,3,17,37,168,0,0,59.29054,...,37,168,0,0,2,45,-14.35467,22,3,7
4,Geno Smith,QB,2520,7,24,34,362,1,1,102.81863,...,34,362,1,1,4,39,11.57749,16,1,6
5,Jared Goff,QB,1540,16,31,39,225,1,1,88.56838,...,39,225,1,1,4,43,-0.90195,12,0,6
6,Dak Prescott,QB,1200,4,21,34,188,0,0,76.59314,...,34,188,0,0,0,35,-1.13336,12,3,9
7,Patrick Mahomes,QB,2310,15,24,39,258,1,0,89.47650,...,39,258,1,0,2,47,8.52113,12,2,2
8,Baker Mayfield,QB,4900,6,17,32,167,3,0,99.34896,...,32,167,3,0,1,37,8.38650,15,0,6
9,Sam Darnold,QB,4600,14,16,23,150,0,0,87.22826,...,23,150,0,0,1,25,-11.58244,8,0,3

In [4]:
receiving_stats = nflpro_api.get_receiving_stats(
        limit=10,
        season=2025,
        season_type=None,
        week="WEEK_1",
)
if receiving_stats:
        print("Receiving Stats:")
        print(receiving_stats)

# nflpro_api.stats_to_dataframe(receiving_stats)

Receiving Stats:
{'limit': 10, 'season': 2025, 'week': 'WEEK_1', 'total': 325, 'receivers': [{'rt': 11, 'tgt': 2, 'rec': 2, 'yds': 35, 'td': 1, 'int': 0, 'rating': 158.33333, 'catch': 1, 'xCatch': 0.47445, 'croe': 0.52555, 'ydsRec': 17.5, 'ydsRt': 3.18182, 'epa': 2.25579, 'epaTgt': 1.1279, 'epaRt': 0.20507, 'drop': 0, 'dropTgt': 0, 'yac': 6, 'xYac': 3, 'yacoe': 3, 'yacRec': 3, 'avgSep': 0.97449, 'ay': 29.68, 'ayTgt': 14.84, 'tgtRt': 0.18182, 'avgRtDep': 12.18182, 'ezTgt': 0, 'ezRec': 0, 'deepTgtPct': 0.5, 'twPct': 0.5, 'nflId': '39973', 'weekSlug': 'WEEK_1', 'opponentTeamId': '0610', 'gameId': 2025090712, 'finalScore': '40-41', 'displayName': 'DeAndre Hopkins', 'isHome': False, 'gameResult': 'L', 'positionGroup': 'WR', 'ngsPositionGroup': 'WR', 'fapiGameId': 'f61dee18-311e-11f0-b670-ae1250fadad1', 'headshot': 'https://static.www.nfl.com/image/upload/{formatInstructions}/league/snvo6holyfdjmrlqxqxu', 'teamId': '0325', 'jerseyNumber': 10, 'position': 'WR', 'shortName': 'D.Hopkins', 'ngsPosition': 'WR', 'gp': 1, 'gs': 0, 'tg': 1, 'totalTg': 1, 'qr': True, 'rtPG': 11, 'tgtPG': 2, 'recPG': 2, 'ydsPG': 35, 'tdPG': 1, 'intPG': 0, 'epaPG': 2.25579, 'dropPG': 0, 'yacPG': 6, 'xYacPG': 3, 'yacoePG': 3, 'ayPG': 29.68, 'ezTgtPG': 0, 'ezRecPG': 0}, {'rt': 27, 'tgt': 5, 'rec': 3, 'yds': 26, 'td': 1, 'int': 0, 'rating': 113.33333, 'catch': 0.6, 'xCatch': 0.62486, 'croe': -0.02486, 'ydsRec': 8.66667, 'ydsRt': 0.96296, 'epa': -0.69253, 'epaTgt': -0.13851, 'epaRt': -0.02565, 'drop': 1, 'dropTgt': 0.2, 'yac': 6, 'xYac': 5, 'yacoe': 1, 'yacRec': 2, 'avgSep': 2.46586, 'ay': 41.34, 'ayTgt': 8.268, 'tgtRt': 0.18519, 'avgRtDep': 7.2963, 'ezTgt': 0, 'ezRec': 0, 'deepTgtPct': 0, 'twPct': 0.2, 'nflId': '39983', 'weekSlug': 'WEEK_1', 'opponentTeamId': '3410', 'gameId': 2025090707, 'finalScore': '21-6', 'displayName': 'Zach Ertz', 'isHome': True, 'gameResult': 'W', 'positionGroup': 'TE', 'ngsPositionGroup': 'WR', 'fapiGameId': 'f591a57f-311e-11f0-b670-ae1250fadad1', 'headshot': 'https://static.www.nfl.com/image/upload/{formatInstructions}/league/xktmmeumuoglbuam75iz', 'teamId': '5110', 'jerseyNumber': 86, 'position': 'TE', 'shortName': 'Z.Ertz', 'ngsPosition': 'WR', 'gp': 1, 'gs': 1, 'tg': 1, 'totalTg': 1, 'qr': True, 'rtPG': 27, 'tgtPG': 5, 'recPG': 3, 'ydsPG': 26, 'tdPG': 1, 'intPG': 0, 'epaPG': -0.69253, 'dropPG': 1, 'yacPG': 6, 'xYacPG': 5, 'yacoePG': 1, 'ayPG': 41.34, 'ezTgtPG': 0, 'ezRecPG': 0}, {'rt': 33, 'tgt': 4, 'rec': 2, 'yds': 47, 'td': 1, 'int': 0, 'rating': 132.29167, 'catch': 0.5, 'xCatch': 0.69208, 'croe': -0.19208, 'ydsRec': 23.5, 'ydsRt': 1.42424, 'epa': 2.40099, 'epaTgt': 0.60025, 'epaRt': 0.07276, 'drop': 0, 'dropTgt': 0, 'yac': 26, 'xYac': 24, 'yacoe': 2, 'yacRec': 13, 'avgSep': 3.35058, 'ay': 23.39, 'ayTgt': 5.8475, 'tgtRt': 0.12121, 'avgRtDep': 6.06061, 'ezTgt': 0, 'ezRec': 0, 'deepTgtPct': 0, 'twPct': 0, 'nflId': '40011', 'weekSlug': 'WEEK_1', 'opponentTeamId': '4400', 'gameId': 2025090500, 'finalScore': '21-27', 'displayName': 'Travis Kelce', 'isHome': False, 'gameResult': 'L', 'positionGroup': 'TE', 'ngsPositionGroup': 'WR', 'fapiGameId': 'f5919071-311e-11f0-b670-ae1250fadad1', 'headshot': 'https://static.www.nfl.com/image/upload/{formatInstructions}/league/ebc5j60djpinc9elvlc5', 'teamId': '2310', 'jerseyNumber': 87, 'position': 'TE', 'shortName': 'T.Kelce', 'ngsPosition': 'WR', 'gp': 1, 'gs': 1, 'tg': 1, 'totalTg': 1, 'qr': True, 'rtPG': 33, 'tgtPG': 4, 'recPG': 2, 'ydsPG': 47, 'tdPG': 1, 'intPG': 0, 'epaPG': 2.40099, 'dropPG': 0, 'yacPG': 26, 'xYacPG': 24, 'yacoePG': 2, 'ayPG': 23.39, 'ezTgtPG': 0, 'ezRecPG': 0}, {'rt': 28, 'tgt': 10, 'rec': 7, 'yds': 68, 'td': 1, 'int': 0, 'rating': 122.08333, 'catch': 0.7, 'xCatch': 0.69084, 'croe': 0.00916, 'ydsRec': 9.71429, 'ydsRt': 2.42857, 'epa': 5.97379, 'epaTgt': 0.59738, 'epaRt': 0.21335, 'drop': 1, 'dropTgt': 0.1, 'yac': 20, 'xYac': 22, 'yacoe': -2, 'yacRec': 2.85714, 'avgSep': 3.49728, 'ay': 89.44, 'ayTgt': 8.944, 'tgtRt': 0.35714, 'avgRtDep': 8.28571, 'ezTgt': 1, 'ezRec': 1, 'deepTgtPct': 0.1, 'twPct': 0.1, 'nflId': '40024', 'weekSlug': 'WEEK_1', 'opponentTeamId': '2310', 'gameId': 2025090500, 'finalScore': '27-21', 'displayName': 'Keenan Allen', 'isHome': True, 'gameResult': 'W', 'positionGroup': 'WR', 'ngsPositionGroup': 'WR', 'fapiGameId': 'f5919071-311e-11f0-b670-ae1250fadad1', 'headshot': 'https://static.www.nfl.com/image/upload/{formatInstructions}/league/lngo1onvkcqjnq7ozkuu', 'teamId': '4400', 'jerseyNumber': 13, 'position': 'WR', 'shortName': 'K.Allen', 'ngsPosition': 'WR', 'gp': 1, 'gs': 1, 'tg': 1, 'totalTg': 1, 'qr': True, 'rtPG': 28, 'tgtPG': 10, 'recPG': 7, 'ydsPG': 68, 'tdPG': 1, 'intPG': 0, 'epaPG': 5.97379, 'dropPG': 1, 'yacPG': 20, 'xYacPG': 22, 'yacoePG': -2, 'ayPG': 89.44, 'ezTgtPG': 1, 'ezRecPG': 1}, {'rt': 14, 'tgt': 2, 'rec': 2, 'yds': 32, 'td': 0, 'int': 0, 'rating': 118.75, 'catch': 1, 'xCatch': 0.82225, 'croe': 0.17775, 'ydsRec': 16, 'ydsRt': 2.28571, 'epa': 2.03005, 'epaTgt': 1.01502, 'epaRt': 0.145, 'drop': 0, 'dropTgt': 0, 'yac': 11, 'xYac': 15, 'yacoe': -4, 'yacRec': 5.5, 'avgSep': 6.67754, 'ay': 20.25, 'ayTgt': 10.125, 'tgtRt': 0.14286, 'avgRtDep': 4.5, 'ezTgt': 0, 'ezRec': 0, 'deepTgtPct': 0.5, 'twPct': 0, 'nflId': '40078', 'weekSlug': 'WEEK_1', 'opponentTeamId': '4600', 'gameId': 2025090709, 'finalScore': '17-13', 'displayName': 'Kyle Juszczyk', 'isHome': False, 'gameResult': 'W', 'positionGroup': 'RB', 'ngsPositionGroup': 'TE', 'fapiGameId': 'f61ddd60-311e-11f0-b670-ae1250fadad1', 'headshot': 'https://static.www.nfl.com/image/upload/{formatInstructions}/league/qflumv1aag7yw9mgwpga', 'teamId': '4500', 'jerseyNumber': 44, 'position': 'FB', 'shortName': 'K.Juszczyk', 'ngsPosition': 'TE', 'gp': 1, 'gs': 1, 'tg': 1, 'totalTg': 1, 'qr': True, 'rtPG': 14, 'tgtPG': 2, 'recPG': 2, 'ydsPG': 32, 'tdPG': 0, 'intPG': 0, 'epaPG': 2.03005, 'dropPG': 0, 'yacPG': 11, 'xYacPG': 15, 'yacoePG': -4, 'ayPG': 20.25, 'ezTgtPG': 0, 'ezRecPG': 0}, {'rt': 16, 'tgt': 1, 'rec': 0, 'yds': 0, 'td': 0, 'int': 0, 'rating': 39.58333, 'catch': 0, 'xCatch': 0.8402, 'croe': -0.8402, 'ydsRec': 0, 'ydsRt': 0, 'epa': -1.90496, 'epaTgt': -1.90496, 'epaRt': -0.11906, 'drop': 1, 'dropTgt': 1, 'yac': 0, 'xYac': 0, 'yacoe': 0, 'yacRec': 0, 'avgSep': 3.23125, 'ay': 7.25, 'ayTgt': 7.25, 'tgtRt': 0.0625, 'avgRtDep': 9.875, 'ezTgt': 0, 'ezRec': 0, 'deepTgtPct': 0, 'twPct': 0, 'nflId': '40488', 'weekSlug': 'WEEK_1', 'opponentTeamId': '0810', 'gameId': 2025090800, 'finalScore': '27-24', 'displayName': 'Adam Thielen', 'isHome': False, 'gameResult': 'W', 'positionGroup': 'WR', 'ngsPositionGroup': 'WR', 'fapiGameId': 'f61df2b7-311e-11f0-b670-ae1250fadad1', 'headshot': 'https://static.www.nfl.com/image/upload/{formatInstructions}/league/peomvmvfqe68czeu8qek', 'teamId': '3000', 'jerseyNumber': 19, 'position': 'WR', 'shortName': 'A.Thielen', 'ngsPosition': 'WR', 'gp': 1, 'gs': 0, 'tg': 1, 'totalTg': 1, 'qr': False, 'rtPG': 16, 'tgtPG': 1, 'recPG': 0, 'ydsPG': 0, 'tdPG': 0, 'intPG': 0, 'epaPG': -1.90496, 'dropPG': 1, 'yacPG': 0, 'xYacPG': 0, 'yacoePG': 0, 'ayPG': 7.25, 'ezTgtPG': 0, 'ezRecPG': 0}, {'rt': 29, 'tgt': 8, 'rec': 5, 'yds': 51, 'td': 0, 'int': 0, 'rating': 80.72917, 'catch': 0.625, 'xCatch': 0.52202, 'croe': 0.10298, 'ydsRec': 10.2, 'ydsRt': 1.75862, 'epa': 3.62234, 'epaTgt': 0.45279, 'epaRt': 0.12491, 'drop': 0, 'dropTgt': 0, 'yac': 4, 'xYac': 11, 'yacoe': -7, 'yacRec': 0.8, 'avgSep': 1.79782, 'ay': 104.03, 'ayTgt': 13.00375, 'tgtRt': 0.27586, 'avgRtDep': 13.24138, 'ezTgt': 0, 'ezRec': 0, 'deepTgtPct': 0.125, 'twPct': 0.375, 'nflId': '41233', 'weekSlug': 'WEEK_1', 'opponentTeamId': '0200', 'gameId': 2025090700, 'finalScore': '23-20', 'displayName': 'Mike Evans', 'isHome': False, 'gameResult': 'W', 'positionGroup': 'WR', 'ngsPositionGroup': 'WR', 'fapiGameId': 'f5919639-311e-11f0-b670-ae1250fadad1', 'headshot': 'https://static.www.nfl.com/image/upload/{formatInstructions}/league/yaxorbdsvk1ucfuiyrkj', 'teamId': '4900', 'jerseyNumber': 13, 'position': 'WR', 'shortName': 'M.Evans', 'ngsPosition': 'WR', 'gp': 1, 'gs': 1, 'tg': 1, 'totalTg': 1, 'qr': True, 'rtPG': 29, 'tgtPG': 8, 'recPG': 5, 'ydsPG': 51, 'tdPG': 0, 'intPG': 0, 'epaPG': 3.62234, 'dropPG': 0, 'yacPG': 4, 'xYacPG': 11, 'yacoePG': -7, 'ayPG': 104.03, 'ezTgtPG': 0, 'ezRecPG': 0}, {'rt': 38, 'tgt': 4, 'rec': 3, 'yds': 26, 'td': 0, 'int': 0, 'rating': 91.66667, 'catch': 0.75, 'xCatch': 0.76465, 'croe': -0.01465, 'ydsRec': 8.66667, 'ydsRt': 0.68421, 'epa': 1.25311, 'epaTgt': 0.31328, 'epaRt': 0.03298, 'drop': 1, 'dropTgt': 0.25, 'yac': 21, 'xYac': 11, 'yacoe': 10, 'yacRec': 7, 'avgSep': 6.62044, 'ay': 17.23, 'ayTgt': 4.3075, 'tgtRt': 0.10526, 'avgRtDep': 9.81081, 'ezTgt': 0, 'ezRec': 0, 'deepTgtPct': 0, 'twPct': 0, 'nflId': '41246', 'weekSlug': 'WEEK_1', 'opponentTeamId': '3800', 'gameId': 2025090705, 'finalScore': '13-20', 'displayName': 'Brandin Cooks', 'isHome': True, 'gameResult': 'L', 'positionGroup': 'WR', 'ngsPositionGroup': 'WR', 'fapiGameId': 'f591a18c-311e-11f0-b670-ae1250fadad1', 'headshot': 'https://static.www.nfl.com/image/upload/{formatInstructions}/league/krz3gv9jjs92arlctvqf', 'teamId': '3300', 'jerseyNumber': 10, 'position': 'WR', 'shortName': 'B.Cooks', 'ngsPosition': 'WR', 'gp': 1, 'gs': 0, 'tg': 1, 'totalTg': 1, 'qr': True, 'rtPG': 38, 'tgtPG': 4, 'recPG': 3, 'ydsPG': 26, 'tdPG': 0, 'intPG': 0, 'epaPG': 1.25311, 'dropPG': 1, 'yacPG': 21, 'xYacPG': 11, 'yacoePG': 10, 'ayPG': 17.23, 'ezTgtPG': 0, 'ezRecPG': 0}, {'rt': 29, 'tgt': 8, 'rec': 4, 'yds': 51, 'td': 0, 'int': 0, 'rating': 70.3125, 'catch': 0.5, 'xCatch': 0.5552, 'croe': -0.0552, 'ydsRec': 12.75, 'ydsRt': 1.75862, 'epa': 3.94883, 'epaTgt': 0.4936, 'epaRt': 0.13617, 'drop': 0, 'dropTgt': 0, 'yac': 11, 'xYac': 7, 'yacoe': 4, 'yacRec': 2.75, 'avgSep': 1.61925, 'ay': 68.23, 'ayTgt': 8.52875, 'tgtRt': 0.27586, 'avgRtDep': 11, 'ezTgt': 0, 'ezRec': 0, 'deepTgtPct': 0, 'twPct': 0.25, 'nflId': '41282', 'weekSlug': 'WEEK_1', 'opponentTeamId': '2120', 'gameId': 2025090711, 'finalScore': '14-9', 'displayName': 'Davante Adams', 'isHome': True, 'gameResult': 'W', 'positionGroup': 'WR', 'ngsPositionGroup': 'WR', 'fapiGameId': 'f61de743-311e-11f0-b670-ae1250fadad1', 'headshot': 'https://static.www.nfl.com/image/upload/{formatInstructions}/league/qtonvcqpixixqhc6lhnc', 'teamId': '2510', 'jerseyNumber': 17, 'position': 'WR', 'shortName': 'D.Adams', 'ngsPosition': 'WR', 'gp': 1, 'gs': 1, 'tg': 1, 'totalTg': 1, 'qr': True, 'rtPG': 29, 'tgtPG': 8, 'recPG': 4, 'ydsPG': 51, 'tdPG': 0, 'intPG': 0, 'epaPG': 3.94883, 'dropPG': 0, 'yacPG': 11, 'xYacPG': 7, 'yacoePG': 4, 'ayPG': 68.23, 'ezTgtPG': 0, 'ezRecPG': 0}, {'rt': 3, 'tgt': 0, 'rec': 0, 'yds': 0, 'td': 0, 'int': 0, 'rating': 0, 'catch': 0, 'xCatch': 0, 'croe': 0, 'ydsRec': 0, 'ydsRt': 0, 'epa': 0, 'epaTgt': 0, 'epaRt': 0, 'drop': 0, 'dropTgt': 0, 'yac': 0, 'xYac': 0, 'yacoe': 0, 'yacRec': 0, 'avgSep': 0, 'ay': 0, 'ayTgt': 0, 'tgtRt': 0, 'avgRtDep': 6, 'ezTgt': 0, 'ezRec': 0, 'deepTgtPct': 0, 'twPct': 0, 'nflId': '42302', 'weekSlug': 'WEEK_1', 'opponentTeamId': '5110', 'gameId': 2025090707, 'finalScore': '6-21', 'displayName': 'Chris Manhertz', 'isHome': False, 'gameResult': 'L', 'positionGroup': 'TE', 'ngsPositionGroup': 'TE', 'fapiGameId': 'f591a57f-311e-11f0-b670-ae1250fadad1', 'headshot': 'https://static.www.nfl.com/image/upload/{formatInstructions}/league/azx76rspzgxfogsqhxet', 'teamId': '3410', 'jerseyNumber': 85, 'position': 'TE', 'shortName': 'C.Manhertz', 'ngsPosition': 'TE', 'gp': 1, 'gs': 1, 'tg': 1, 'totalTg': 1, 'qr': False, 'rtPG': 3, 'tgtPG': 0, 'recPG': 0, 'ydsPG': 0, 'tdPG': 0, 'intPG': 0, 'epaPG': 0, 'dropPG': 0, 'yacPG': 0, 'xYacPG': 0, 'yacoePG': 0, 'ayPG': 0, 'ezTgtPG': 0, 'ezRecPG': 0}]}

In [5]:
rushing_stats = nflpro_api.get_rushing_stats(
        limit=10,
        season=2025,
        season_type=None,
        week="WEEK_1",
)
if rushing_stats:
        print("Rushing Stats:")
        print(rushing_stats)

# nflpro_api.stats_to_dataframe(rushing_stats)

Rushing Stats:
{'limit': 10, 'season': 2025, 'week': 'WEEK_1', 'total': 137, 'rushers': [{'att': 1, 'yds': -1, 'td': 0, 'ypc': -1, 'epa': 0, 'epaAtt': 0, 'xRy': 0, 'xYpc': 0, 'ryoe': 0, 'ryoeAtt': 0, 'yaco': 0, 'yacoAtt': 0, 'ybco': 0, 'success': 0, 'fum': 0, 'lost': 0, 'rush10PYds': 0, 'rush15PMph': 0, 'rush20PMph': 0, 'eff': 0.15, 'inTPct': 0, 'stBoxPct': 0, 'underPct': 0, 'nflId': '29851', 'weekSlug': 'WEEK_1', 'opponentTeamId': '3430', 'gameId': 2025090706, 'finalScore': '34-32', 'displayName': 'Aaron Rodgers', 'isHome': False, 'gameResult': 'W', 'positionGroup': 'QB', 'ngsPositionGroup': 'QB', 'fapiGameId': 'f591a382-311e-11f0-b670-ae1250fadad1', 'headshot': 'https://static.www.nfl.com/image/upload/{formatInstructions}/league/dypvakakxhccxs67tb0y', 'teamId': '3900', 'jerseyNumber': 8, 'position': 'QB', 'shortName': 'A.Rodgers', 'ngsPosition': 'QB', 'gp': 1, 'gs': 1, 'tg': 1, 'totalTg': 1, 'qr': False, 'attPG': 1, 'ydsPG': -1, 'tdPG': 0, 'epaPG': 0, 'xRyPG': 0, 'ryoePG': 0, 'yacoPG': 0, 'ybcoPG': 0, 'fumPG': 0, 'lostPG': 0, 'rush10PYdsPG': 0, 'rush15PMphPG': 0, 'rush20PMphPG': 0}, {'att': 2, 'yds': 6, 'td': 0, 'ypc': 3, 'epa': 0.15354, 'epaAtt': 0.07677, 'xRy': 8.2028, 'xYpc': 4.1014, 'ryoe': -2.2028, 'ryoeAtt': -1.1014, 'yaco': 2.14, 'yacoAtt': 1.07, 'ybco': 3.86, 'success': 0.5, 'fum': 0, 'lost': 0, 'rush10PYds': 0, 'rush15PMph': 1, 'rush20PMph': 0, 'eff': 18.365, 'inTPct': 0.5, 'stBoxPct': 0.5, 'underPct': 0.5, 'nflId': '33099', 'weekSlug': 'WEEK_1', 'opponentTeamId': '0920', 'gameId': 2025090701, 'finalScore': '16-17', 'displayName': 'Joe Flacco', 'isHome': True, 'gameResult': 'L', 'positionGroup': 'QB', 'ngsPositionGroup': 'QB', 'fapiGameId': 'f5919910-311e-11f0-b670-ae1250fadad1', 'headshot': 'https://static.www.nfl.com/image/upload/{formatInstructions}/league/vbqptn8emdlbeaz1kvmx', 'teamId': '1050', 'jerseyNumber': 15, 'position': 'QB', 'shortName': 'J.Flacco', 'ngsPosition': 'QB', 'gp': 1, 'gs': 1, 'tg': 1, 'totalTg': 1, 'qr': False, 'attPG': 2, 'ydsPG': 6, 'tdPG': 0, 'epaPG': 0.15354, 'xRyPG': 8.2028, 'ryoePG': -2.2028, 'yacoPG': 2.14, 'ybcoPG': 3.86, 'fumPG': 0, 'lostPG': 0, 'rush10PYdsPG': 0, 'rush15PMphPG': 1, 'rush20PMphPG': 0}, {'att': 4, 'yds': -2, 'td': 0, 'ypc': -0.5, 'epa': -4.04489, 'epaAtt': -1.01122, 'xRy': 1, 'xYpc': 1, 'ryoe': -1, 'ryoeAtt': -1, 'yaco': 17.72, 'yacoAtt': 4.43, 'ybco': -17.72, 'success': 0, 'fum': 1, 'lost': 0, 'rush10PYds': 0, 'rush15PMph': 0, 'rush20PMph': 0, 'eff': 5.73, 'inTPct': 0.5, 'stBoxPct': 0.75, 'underPct': 0.25, 'nflId': '34452', 'weekSlug': 'WEEK_1', 'opponentTeamId': '2120', 'gameId': 2025090711, 'finalScore': '14-9', 'displayName': 'Matthew Stafford', 'isHome': True, 'gameResult': 'W', 'positionGroup': 'QB', 'ngsPositionGroup': 'QB', 'fapiGameId': 'f61de743-311e-11f0-b670-ae1250fadad1', 'headshot': 'https://static.www.nfl.com/image/upload/{formatInstructions}/league/svxl2pk2cuqf26zrhii4', 'teamId': '2510', 'jerseyNumber': 9, 'position': 'QB', 'shortName': 'M.Stafford', 'ngsPosition': 'QB', 'gp': 1, 'gs': 1, 'tg': 1, 'totalTg': 1, 'qr': False, 'attPG': 4, 'ydsPG': -2, 'tdPG': 0, 'epaPG': -4.04489, 'xRyPG': 1, 'ryoePG': -1, 'yacoPG': 17.72, 'ybcoPG': -17.72, 'fumPG': 1, 'lostPG': 0, 'rush10PYdsPG': 0, 'rush15PMphPG': 0, 'rush20PMphPG': 0}, {'att': 8, 'yds': 44, 'td': 0, 'ypc': 5.5, 'epa': 2.01541, 'epaAtt': 0.25193, 'xRy': 60.99646, 'xYpc': 7.62456, 'ryoe': -16.99646, 'ryoeAtt': -2.12456, 'yaco': 6.72, 'yacoAtt': 0.84, 'ybco': 37.28, 'success': 0.625, 'fum': 1, 'lost': 0, 'rush10PYds': 1, 'rush15PMph': 3, 'rush20PMph': 0, 'eff': 18.8575, 'inTPct': 0.5, 'stBoxPct': 0.375, 'underPct': 0.375, 'nflId': '38605', 'weekSlug': 'WEEK_1', 'opponentTeamId': '5110', 'gameId': 2025090707, 'finalScore': '6-21', 'displayName': 'Russell Wilson', 'isHome': False, 'gameResult': 'L', 'positionGroup': 'QB', 'ngsPositionGroup': 'QB', 'fapiGameId': 'f591a57f-311e-11f0-b670-ae1250fadad1', 'headshot': 'https://static.www.nfl.com/image/upload/{formatInstructions}/league/vkstxj0evgkjiycu4glc', 'teamId': '3410', 'jerseyNumber': 3, 'position': 'QB', 'shortName': 'R.Wilson', 'ngsPosition': 'QB', 'gp': 1, 'gs': 1, 'tg': 1, 'totalTg': 1, 'qr': True, 'attPG': 8, 'ydsPG': 44, 'tdPG': 0, 'epaPG': 2.01541, 'xRyPG': 60.99646, 'ryoePG': -16.99646, 'yacoPG': 6.72, 'ybcoPG': 37.28, 'fumPG': 1, 'lostPG': 0, 'rush10PYdsPG': 1, 'rush15PMphPG': 3, 'rush20PMphPG': 0}, {'att': 2, 'yds': 10, 'td': 0, 'ypc': 5, 'epa': 0.05454, 'epaAtt': 0.02727, 'xRy': 8.00816, 'xYpc': 8.00816, 'ryoe': 2.99184, 'ryoeAtt': 2.99184, 'yaco': 0, 'yacoAtt': 0, 'ybco': 11, 'success': 0.5, 'fum': 0, 'lost': 0, 'rush10PYds': 1, 'rush15PMph': 1, 'rush20PMph': 0, 'eff': 23.245, 'inTPct': 0, 'stBoxPct': 0.5, 'underPct': 0, 'nflId': '39987', 'weekSlug': 'WEEK_1', 'opponentTeamId': '3200', 'gameId': 2025090704, 'finalScore': '20-13', 'displayName': 'Geno Smith', 'isHome': False, 'gameResult': 'W', 'positionGroup': 'QB', 'ngsPositionGroup': 'QB', 'fapiGameId': 'f5919f8e-311e-11f0-b670-ae1250fadad1', 'headshot': 'https://static.www.nfl.com/image/upload/{formatInstructions}/league/tqy0933vz5yogwlefb1s', 'teamId': '2520', 'jerseyNumber': 7, 'position': 'QB', 'shortName': 'G.Smith', 'ngsPosition': 'QB', 'gp': 1, 'gs': 1, 'tg': 1, 'totalTg': 1, 'qr': False, 'attPG': 2, 'ydsPG': 10, 'tdPG': 0, 'epaPG': 0.05454, 'xRyPG': 8.00816, 'ryoePG': 2.99184, 'yacoPG': 0, 'ybcoPG': 11, 'fumPG': 0, 'lostPG': 0, 'rush10PYdsPG': 1, 'rush15PMphPG': 1, 'rush20PMphPG': 0}, {'att': 1, 'yds': -1, 'td': 0, 'ypc': -1, 'epa': 0, 'epaAtt': 0, 'xRy': 0, 'xYpc': 0, 'ryoe': 0, 'ryoeAtt': 0, 'yaco': 0, 'yacoAtt': 0, 'ybco': 0, 'success': 0, 'fum': 0, 'lost': 0, 'rush10PYds': 0, 'rush15PMph': 0, 'rush20PMph': 0, 'eff': 0.12, 'inTPct': 0, 'stBoxPct': 0, 'underPct': 0, 'nflId': '43290', 'weekSlug': 'WEEK_1', 'opponentTeamId': '1800', 'gameId': 2025090710, 'finalScore': '13-27', 'displayName': 'Jared Goff', 'isHome': False, 'gameResult': 'L', 'positionGroup': 'QB', 'ngsPositionGroup': 'QB', 'fapiGameId': 'f61de295-311e-11f0-b670-ae1250fadad1', 'headshot': 'https://static.www.nfl.com/image/upload/{formatInstructions}/league/yggfwr4ak4po9byj0qor', 'teamId': '1540', 'jerseyNumber': 16, 'position': 'QB', 'shortName': 'J.Goff', 'ngsPosition': 'QB', 'gp': 1, 'gs': 1, 'tg': 1, 'totalTg': 1, 'qr': False, 'attPG': 1, 'ydsPG': -1, 'tdPG': 0, 'epaPG': 0, 'xRyPG': 0, 'ryoePG': 0, 'yacoPG': 0, 'ybcoPG': 0, 'fumPG': 0, 'lostPG': 0, 'rush10PYdsPG': 0, 'rush15PMphPG': 0, 'rush20PMphPG': 0}, {'att': 18, 'yds': 169, 'td': 2, 'ypc': 9.38889, 'epa': 0.8956, 'epaAtt': 0.04976, 'xRy': 114.81851, 'xYpc': 6.37881, 'ryoe': 54.18149, 'ryoeAtt': 3.01008, 'yaco': 103.55, 'yacoAtt': 5.75278, 'ybco': 65.45, 'success': 0.38889, 'fum': 1, 'lost': 1, 'rush10PYds': 5, 'rush15PMph': 5, 'rush20PMph': 1, 'eff': 23.08278, 'inTPct': 0.33333, 'stBoxPct': 0.16667, 'underPct': 0.66667, 'nflId': '43334', 'weekSlug': 'WEEK_1', 'opponentTeamId': '0610', 'gameId': 2025090712, 'finalScore': '40-41', 'displayName': 'Derrick Henry', 'isHome': False, 'gameResult': 'L', 'positionGroup': 'RB', 'ngsPositionGroup': 'RB', 'fapiGameId': 'f61dee18-311e-11f0-b670-ae1250fadad1', 'headshot': 'https://static.www.nfl.com/image/upload/{formatInstructions}/league/jxtikemnvpkw9r0ex2wv', 'teamId': '0325', 'jerseyNumber': 22, 'position': 'RB', 'shortName': 'D.Henry', 'ngsPosition': 'RB', 'gp': 1, 'gs': 1, 'tg': 1, 'totalTg': 1, 'qr': True, 'attPG': 18, 'ydsPG': 169, 'tdPG': 2, 'epaPG': 0.8956, 'xRyPG': 114.81851, 'ryoePG': 54.18149, 'yacoPG': 103.55, 'ybcoPG': 65.45, 'fumPG': 1, 'lostPG': 1, 'rush10PYdsPG': 5, 'rush15PMphPG': 5, 'rush20PMphPG': 1}, {'att': 1, 'yds': 3, 'td': 0, 'ypc': 3, 'epa': -0.2875, 'epaAtt': -0.2875, 'xRy': 5.14141, 'xYpc': 5.14141, 'ryoe': -2.14141, 'ryoeAtt': -2.14141, 'yaco': 0, 'yacoAtt': 0, 'ybco': 3, 'success': 0, 'fum': 0, 'lost': 0, 'rush10PYds': 0, 'rush15PMph': 1, 'rush20PMph': 0, 'eff': 43.13, 'inTPct': 0, 'stBoxPct': 0, 'underPct': 1, 'nflId': '43424', 'weekSlug': 'WEEK_1', 'opponentTeamId': '3700', 'gameId': 2025090400, 'finalScore': '20-24', 'displayName': 'Dak Prescott', 'isHome': False, 'gameResult': 'L', 'positionGroup': 'QB', 'ngsPositionGroup': 'QB', 'fapiGameId': 'f5908b6d-311e-11f0-b670-ae1250fadad1', 'headshot': 'https://static.www.nfl.com/image/upload/{formatInstructions}/league/blixemm3s9sa4gmqk5yn', 'teamId': '1200', 'jerseyNumber': 4, 'position': 'QB', 'shortName': 'D.Prescott', 'ngsPosition': 'QB', 'gp': 1, 'gs': 1, 'tg': 1, 'totalTg': 1, 'qr': False, 'attPG': 1, 'ydsPG': 3, 'tdPG': 0, 'epaPG': -0.2875, 'xRyPG': 5.14141, 'ryoePG': -2.14141, 'yacoPG': 0, 'ybcoPG': 3, 'fumPG': 0, 'lostPG': 0, 'rush10PYdsPG': 0, 'rush15PMphPG': 1, 'rush20PMphPG': 0}, {'att': 22, 'yds': 69, 'td': 0, 'ypc': 3.13636, 'epa': -6.08194, 'epaAtt': -0.27645, 'xRy': 94.36345, 'xYpc': 4.28925, 'ryoe': -25.36345, 'ryoeAtt': -1.15288, 'yaco': 51.42, 'yacoAtt': 2.33727, 'ybco': 17.58, 'success': 0.36364, 'fum': 0, 'lost': 0, 'rush10PYds': 1, 'rush15PMph': 2, 'rush20PMph': 0, 'eff': 14.39864, 'inTPct': 0.45455, 'stBoxPct': 0.09091, 'underPct': 0.72727, 'nflId': '44820', 'weekSlug': 'WEEK_1', 'opponentTeamId': '4600', 'gameId': 2025090709, 'finalScore': '17-13', 'displayName': 'Christian McCaffrey', 'isHome': False, 'gameResult': 'W', 'positionGroup': 'RB', 'ngsPositionGroup': 'RB', 'fapiGameId': 'f61ddd60-311e-11f0-b670-ae1250fadad1', 'headshot': 'https://static.www.nfl.com/image/upload/{formatInstructions}/league/resjdwihunsqckohcorj', 'teamId': '4500', 'jerseyNumber': 23, 'position': 'RB', 'shortName': 'C.McCaffrey', 'ngsPosition': 'RB', 'gp': 1, 'gs': 1, 'tg': 1, 'totalTg': 1, 'qr': True, 'attPG': 22, 'ydsPG': 69, 'tdPG': 0, 'epaPG': -6.08194, 'xRyPG': 94.36345, 'ryoePG': -25.36345, 'yacoPG': 51.42, 'ybcoPG': 17.58, 'fumPG': 0, 'lostPG': 0, 'rush10PYdsPG': 1, 'rush15PMphPG': 2, 'rush20PMphPG': 0}, {'att': 6, 'yds': 57, 'td': 1, 'ypc': 9.5, 'epa': 7.23097, 'epaAtt': 1.20516, 'xRy': 49.38472, 'xYpc': 8.23079, 'ryoe': 7.61528, 'ryoeAtt': 1.26921, 'yaco': 12.44, 'yacoAtt': 2.07333, 'ybco': 44.56, 'success': 0.83333, 'fum': 0, 'lost': 0, 'rush10PYds': 4, 'rush15PMph': 5, 'rush20PMph': 0, 'eff': 36.56, 'inTPct': 0, 'stBoxPct': 0.16667, 'underPct': 0.33333, 'nflId': '44822', 'weekSlug': 'WEEK_1', 'opponentTeamId': '4400', 'gameId': 2025090500, 'finalScore': '21-27', 'displayName': 'Patrick Mahomes', 'isHome': False, 'gameResult': 'L', 'positionGroup': 'QB', 'ngsPositionGroup': 'QB', 'fapiGameId': 'f5919071-311e-11f0-b670-ae1250fadad1', 'headshot': 'https://static.www.nfl.com/image/upload/{formatInstructions}/league/iireqbn32cpg9fn4sfy7', 'teamId': '2310', 'jerseyNumber': 15, 'position': 'QB', 'shortName': 'P.Mahomes', 'ngsPosition': 'QB', 'gp': 1, 'gs': 1, 'tg': 1, 'totalTg': 1, 'qr': False, 'attPG': 6, 'ydsPG': 57, 'tdPG': 1, 'epaPG': 7.23097, 'xRyPG': 49.38472, 'ryoePG': 7.61528, 'yacoPG': 12.44, 'ybcoPG': 44.56, 'fumPG': 0, 'lostPG': 0, 'rush10PYdsPG': 4, 'rush15PMphPG': 5, 'rush20PMphPG': 0}]}

In [6]:
team_offense_stats = nflpro_api.get_team_offense_stats(
        limit=10,
        season=2025,
        season_type=None,
        week="WEEK_1",
)
if team_offense_stats:
        print("Team Offense Stats:")
        print(team_offense_stats)

# nflpro_api.stats_to_dataframe(team_offense_stats)

Team Offense Stats:
{'limit': 10, 'season': 2025, 'week': 'WEEK_1', 'total': 32, 'offense': [{'total': 71, 'pass': 43, 'run': 28, 'yds': 358, 'passPct': 0.60563, 'ypp': 5.04225, 'td': 2, 'epa': 2.77162, 'epaPP': 0.03904, 'passYds': 289, 'passYpp': 6.72093, 'epaPass': 9.06315, 'epaPassPP': 0.21077, 'rushYds': 69, 'rushYpp': 2.46429, 'epaRush': -6.29153, 'epaRushPP': -0.2247, 'ttt': 2.55883, 'qbp': 20, 'qbpPct': 0.43478, 'sackedYds': 9, 'ryoe': -30.68997, 'weekSlug': 'WEEK_1', 'gameId': 2025090700, 'fapiGameId': 'f5919639-311e-11f0-b670-ae1250fadad1', 'opponentTeamId': '4900', 'gameResult': 'L', 'finalScore': '20-23', 'isHome': True, 'teamId': '0200', 'gp': 1, 'ppg': 20, 'ypg': 358, 'passYpg': 289, 'rushYpg': 69, 'sackedYpg': 9}, {'total': 50, 'pass': 21, 'run': 29, 'yds': 432, 'passPct': 0.42, 'ypp': 8.64, 'td': 5, 'epa': 14.23646, 'epaPP': 0.28473, 'passYds': 194, 'passYpp': 9.2381, 'epaPass': 7.21603, 'epaPassPP': 0.34362, 'rushYds': 238, 'rushYpp': 8.2069, 'epaRush': 7.02043, 'epaRushPP': 0.24208, 'ttt': 2.69616, 'qbp': 6, 'qbpPct': 0.27273, 'sackedYds': 15, 'ryoe': 67.16903, 'weekSlug': 'WEEK_1', 'gameId': 2025090712, 'fapiGameId': 'f61dee18-311e-11f0-b670-ae1250fadad1', 'opponentTeamId': '0610', 'gameResult': 'L', 'finalScore': '40-41', 'isHome': False, 'teamId': '0325', 'gp': 1, 'ppg': 40, 'ypg': 432, 'passYpg': 194, 'rushYpg': 238, 'sackedYpg': 15}, {'total': 78, 'pass': 47, 'run': 31, 'yds': 497, 'passPct': 0.60256, 'ypp': 6.37179, 'td': 5, 'epa': 17.30934, 'epaPP': 0.22191, 'passYds': 389, 'passYpp': 8.2766, 'epaPass': 14.52757, 'epaPassPP': 0.3091, 'rushYds': 108, 'rushYpp': 3.48387, 'epaRush': 2.78177, 'epaRushPP': 0.08973, 'ttt': 2.98273, 'qbp': 13, 'qbpPct': 0.25, 'sackedYds': 5, 'ryoe': -4.30352, 'weekSlug': 'WEEK_1', 'gameId': 2025090712, 'fapiGameId': 'f61dee18-311e-11f0-b670-ae1250fadad1', 'opponentTeamId': '0325', 'gameResult': 'W', 'finalScore': '41-40', 'isHome': True, 'teamId': '0610', 'gp': 1, 'ppg': 41, 'ypg': 497, 'passYpg': 389, 'rushYpg': 108, 'sackedYpg': 5}, {'total': 61, 'pass': 36, 'run': 25, 'yds': 255, 'passPct': 0.59016, 'ypp': 4.18033, 'td': 1, 'epa': -19.96737, 'epaPP': -0.32733, 'passYds': 142, 'passYpp': 3.94444, 'epaPass': -19.6633, 'epaPassPP': -0.5462, 'rushYds': 113, 'rushYpp': 4.52, 'epaRush': -0.30407, 'epaRushPP': -0.01216, 'ttt': 2.6574, 'qbp': 16, 'qbpPct': 0.4, 'sackedYds': 12, 'ryoe': 7.01816, 'weekSlug': 'WEEK_1', 'gameId': 2025090703, 'fapiGameId': 'f5919d7e-311e-11f0-b670-ae1250fadad1', 'opponentTeamId': '2250', 'gameResult': 'L', 'finalScore': '10-26', 'isHome': False, 'teamId': '0750', 'gp': 1, 'ppg': 10, 'ypg': 255, 'passYpg': 142, 'rushYpg': 113, 'sackedYpg': 12}, {'total': 63, 'pass': 37, 'run': 26, 'yds': 317, 'passPct': 0.5873, 'ypp': 5.03175, 'td': 2, 'epa': -8.22698, 'epaPP': -0.13059, 'passYds': 198, 'passYpp': 5.35135, 'epaPass': -10.25942, 'epaPassPP': -0.27728, 'rushYds': 119, 'rushYpp': 4.57692, 'epaRush': 2.03244, 'epaRushPP': 0.07817, 'ttt': 3.03629, 'qbp': 15, 'qbpPct': 0.34884, 'sackedYds': 12, 'ryoe': -12.36045, 'weekSlug': 'WEEK_1', 'gameId': 2025090800, 'fapiGameId': 'f61df2b7-311e-11f0-b670-ae1250fadad1', 'opponentTeamId': '3000', 'gameResult': 'L', 'finalScore': '24-27', 'isHome': True, 'teamId': '0810', 'gp': 1, 'ppg': 24, 'ypg': 317, 'passYpg': 198, 'rushYpg': 119, 'sackedYpg': 12}, {'total': 49, 'pass': 26, 'run': 23, 'yds': 141, 'passPct': 0.53061, 'ypp': 2.87755, 'td': 2, 'epa': -9.76935, 'epaPP': -0.19937, 'passYds': 95, 'passYpp': 3.65385, 'epaPass': -1.48982, 'epaPassPP': -0.0573, 'rushYds': 46, 'rushYpp': 2, 'epaRush': -8.27954, 'epaRushPP': -0.35998, 'ttt': 2.75609, 'qbp': 8, 'qbpPct': 0.28571, 'sackedYds': 18, 'ryoe': -8.1162, 'weekSlug': 'WEEK_1', 'gameId': 2025090701, 'fapiGameId': 'f5919910-311e-11f0-b670-ae1250fadad1', 'opponentTeamId': '1050', 'gameResult': 'W', 'finalScore': '17-16', 'isHome': False, 'teamId': '0920', 'gp': 1, 'ppg': 17, 'ypg': 141, 'passYpg': 95, 'rushYpg': 46, 'sackedYpg': 18}, {'total': 71, 'pass': 47, 'run': 24, 'yds': 327, 'passPct': 0.66197, 'ypp': 4.60563, 'td': 2, 'epa': -7.06933, 'epaPP': -0.09957, 'passYds': 278, 'passYpp': 5.91489, 'epaPass': -4.93403, 'epaPassPP': -0.10498, 'rushYds': 49, 'rushYpp': 2.04167, 'epaRush': -2.1353, 'epaRushPP': -0.08897, 'ttt': 2.80387, 'qbp': 17, 'qbpPct': 0.35417, 'sackedYds': 12, 'ryoe': -25.13669, 'weekSlug': 'WEEK_1', 'gameId': 2025090701, 'fapiGameId': 'f5919910-311e-11f0-b670-ae1250fadad1', 'opponentTeamId': '0920', 'gameResult': 'L', 'finalScore': '16-17', 'isHome': True, 'teamId': '1050', 'gp': 1, 'ppg': 16, 'ypg': 327, 'passYpg': 278, 'rushYpg': 49, 'sackedYpg': 12}, {'total': 56, 'pass': 34, 'run': 22, 'yds': 307, 'passPct': 0.60714, 'ypp': 5.48214, 'td': 2, 'epa': -1.65003, 'epaPP': -0.02946, 'passYds': 188, 'passYpp': 5.52941, 'epaPass': -0.84586, 'epaPassPP': -0.02488, 'rushYds': 119, 'rushYpp': 5.40909, 'epaRush': -0.80417, 'epaRushPP': -0.03655, 'ttt': 2.95067, 'qbp': 12, 'qbpPct': 0.34286, 'sackedYds': 0, 'ryoe': 39.98976, 'weekSlug': 'WEEK_1', 'gameId': 2025090400, 'fapiGameId': 'f5908b6d-311e-11f0-b670-ae1250fadad1', 'opponentTeamId': '3700', 'gameResult': 'L', 'finalScore': '20-24', 'isHome': False, 'teamId': '1200', 'gp': 1, 'ppg': 20, 'ypg': 307, 'passYpg': 188, 'rushYpg': 119, 'sackedYpg': 0}, {'total': 71, 'pass': 41, 'run': 30, 'yds': 317, 'passPct': 0.57746, 'ypp': 4.46479, 'td': 2, 'epa': -13.72528, 'epaPP': -0.19331, 'passYds': 166, 'passYpp': 4.04878, 'epaPass': -10.03307, 'epaPassPP': -0.24471, 'rushYds': 151, 'rushYpp': 5.03333, 'epaRush': -3.69221, 'epaRushPP': -0.12307, 'ttt': 2.82725, 'qbp': 8, 'qbpPct': 0.18605, 'sackedYds': 10, 'ryoe': 53.33496, 'weekSlug': 'WEEK_1', 'gameId': 2025090708, 'fapiGameId': 'f61dd155-311e-11f0-b670-ae1250fadad1', 'opponentTeamId': '2100', 'gameResult': 'W', 'finalScore': '20-12', 'isHome': True, 'teamId': '1400', 'gp': 1, 'ppg': 20, 'ypg': 317, 'passYpg': 166, 'rushYpg': 151, 'sackedYpg': 10}, {'total': 65, 'pass': 43, 'run': 22, 'yds': 246, 'passPct': 0.66154, 'ypp': 3.78462, 'td': 1, 'epa': -7.39979, 'epaPP': -0.11384, 'passYds': 200, 'passYpp': 4.65116, 'epaPass': -0.90195, 'epaPassPP': -0.02098, 'rushYds': 46, 'rushYpp': 2.09091, 'epaRush': -6.49784, 'epaRushPP': -0.29536, 'ttt': 3.09079, 'qbp': 12, 'qbpPct': 0.27907, 'sackedYds': 25, 'ryoe': -34.14224, 'weekSlug': 'WEEK_1', 'gameId': 2025090710, 'fapiGameId': 'f61de295-311e-11f0-b670-ae1250fadad1', 'opponentTeamId': '1800', 'gameResult': 'L', 'finalScore': '13-27', 'isHome': False, 'teamId': '1540', 'gp': 1, 'ppg': 13, 'ypg': 246, 'passYpg': 200, 'rushYpg': 46, 'sackedYpg': 25}]}

In [7]:
team_defense_stats = nflpro_api.get_team_defense_stats(
        limit=10,
        season=2025,
        season_type=None,
        week="WEEK_1",
)
if team_defense_stats:
        print("Team Defense Stats:")
        print(team_defense_stats)

# nflpro_api.stats_to_dataframe(team_defense_stats)

Team Defense Stats:
{'limit': 10, 'season': 2025, 'week': 'WEEK_1', 'total': 32, 'defense': [{'total': 56, 'pass': 33, 'run': 23, 'yds': 260, 'passPct': 0.58929, 'ypp': 4.64286, 'td': 3, 'passTd': 3, 'rushTd': 0, 'epa': 4.16746, 'epaPP': 0.07442, 'passYds': 159, 'passYpp': 4.81818, 'epaPass': 4.17553, 'epaPassPP': 0.12653, 'rushYds': 101, 'rushYpp': 4.3913, 'epaRush': -0.00807, 'epaRushPP': -0.00035, 'ttt': 2.94947, 'qbp': 15, 'qbpPct': 0.40541, 'sackedYds': 8, 'ryoe': 5.74903, 'interception': 0, 'forcedFumble': 0, 'fumbleRecovered': 0, 'defensiveTouchdown': 0, 'totalTakeaways': 0, 'weekSlug': 'WEEK_1', 'gameId': 2025090700, 'fapiGameId': 'f5919639-311e-11f0-b670-ae1250fadad1', 'opponentTeamId': '4900', 'gameResult': 'L', 'finalScore': '20-23', 'isHome': True, 'teamId': '0200', 'gp': 1, 'ppg': 23, 'ypg': 260, 'passYpg': 159, 'rushYpg': 101, 'sackedYpg': 8}, {'total': 78, 'pass': 47, 'run': 31, 'yds': 497, 'passPct': 0.60256, 'ypp': 6.37179, 'td': 5, 'passTd': 2, 'rushTd': 3, 'epa': 17.30934, 'epaPP': 0.22191, 'passYds': 389, 'passYpp': 8.2766, 'epaPass': 14.52757, 'epaPassPP': 0.3091, 'rushYds': 108, 'rushYpp': 3.48387, 'epaRush': 2.78177, 'epaRushPP': 0.08973, 'ttt': 2.98273, 'qbp': 13, 'qbpPct': 0.25, 'sackedYds': 5, 'ryoe': -4.30352, 'interception': 0, 'forcedFumble': 1, 'fumbleRecovered': 0, 'defensiveTouchdown': 0, 'totalTakeaways': 0, 'weekSlug': 'WEEK_1', 'gameId': 2025090712, 'fapiGameId': 'f61dee18-311e-11f0-b670-ae1250fadad1', 'opponentTeamId': '0610', 'gameResult': 'L', 'finalScore': '40-41', 'isHome': False, 'teamId': '0325', 'gp': 1, 'ppg': 41, 'ypg': 497, 'passYpg': 389, 'rushYpg': 108, 'sackedYpg': 5}, {'total': 50, 'pass': 21, 'run': 29, 'yds': 432, 'passPct': 0.42, 'ypp': 8.64, 'td': 5, 'passTd': 2, 'rushTd': 3, 'epa': 14.23646, 'epaPP': 0.28473, 'passYds': 194, 'passYpp': 9.2381, 'epaPass': 7.21603, 'epaPassPP': 0.34362, 'rushYds': 238, 'rushYpp': 8.2069, 'epaRush': 7.02043, 'epaRushPP': 0.24208, 'ttt': 2.69616, 'qbp': 6, 'qbpPct': 0.27273, 'sackedYds': 15, 'ryoe': 67.16903, 'interception': 0, 'forcedFumble': 2, 'fumbleRecovered': 1, 'defensiveTouchdown': 0, 'totalTakeaways': 1, 'weekSlug': 'WEEK_1', 'gameId': 2025090712, 'fapiGameId': 'f61dee18-311e-11f0-b670-ae1250fadad1', 'opponentTeamId': '0325', 'gameResult': 'W', 'finalScore': '41-40', 'isHome': True, 'teamId': '0610', 'gp': 1, 'ppg': 40, 'ypg': 432, 'passYpg': 194, 'rushYpg': 238, 'sackedYpg': 15}, {'total': 63, 'pass': 31, 'run': 32, 'yds': 378, 'passPct': 0.49206, 'ypp': 6, 'td': 2, 'passTd': 1, 'rushTd': 1, 'epa': 6.4963, 'epaPP': 0.10312, 'passYds': 178, 'passYpp': 5.74194, 'epaPass': -0.35651, 'epaPassPP': -0.0115, 'rushYds': 200, 'rushYpp': 6.25, 'epaRush': 6.85281, 'epaRushPP': 0.21415, 'ttt': 2.7425, 'qbp': 6, 'qbpPct': 0.18182, 'sackedYds': 0, 'ryoe': 76.64699, 'interception': 1, 'forcedFumble': 0, 'fumbleRecovered': 0, 'defensiveTouchdown': 0, 'totalTakeaways': 1, 'weekSlug': 'WEEK_1', 'gameId': 2025090703, 'fapiGameId': 'f5919d7e-311e-11f0-b670-ae1250fadad1', 'opponentTeamId': '2250', 'gameResult': 'L', 'finalScore': '10-26', 'isHome': False, 'teamId': '0750', 'gp': 1, 'ppg': 26, 'ypg': 378, 'passYpg': 178, 'rushYpg': 200, 'sackedYpg': 0}, {'total': 49, 'pass': 23, 'run': 26, 'yds': 254, 'passPct': 0.46939, 'ypp': 5.18367, 'td': 3, 'passTd': 2, 'rushTd': 1, 'epa': -13.41343, 'epaPP': -0.27374, 'passYds': 134, 'passYpp': 5.82609, 'epaPass': -13.49686, 'epaPassPP': -0.58682, 'rushYds': 120, 'rushYpp': 4.61538, 'epaRush': 0.08342, 'epaRushPP': 0.00321, 'ttt': 2.9446, 'qbp': 7, 'qbpPct': 0.29167, 'sackedYds': 9, 'ryoe': 5.24569, 'interception': 1, 'forcedFumble': 0, 'fumbleRecovered': 0, 'defensiveTouchdown': 1, 'totalTakeaways': 1, 'weekSlug': 'WEEK_1', 'gameId': 2025090800, 'fapiGameId': 'f61df2b7-311e-11f0-b670-ae1250fadad1', 'opponentTeamId': '3000', 'gameResult': 'L', 'finalScore': '24-27', 'isHome': True, 'teamId': '0810', 'gp': 1, 'ppg': 27, 'ypg': 254, 'passYpg': 134, 'rushYpg': 120, 'sackedYpg': 9}, {'total': 71, 'pass': 47, 'run': 24, 'yds': 327, 'passPct': 0.66197, 'ypp': 4.60563, 'td': 2, 'passTd': 1, 'rushTd': 1, 'epa': -7.06933, 'epaPP': -0.09957, 'passYds': 278, 'passYpp': 5.91489, 'epaPass': -4.93403, 'epaPassPP': -0.10498, 'rushYds': 49, 'rushYpp': 2.04167, 'epaRush': -2.1353, 'epaRushPP': -0.08897, 'ttt': 2.80387, 'qbp': 17, 'qbpPct': 0.35417, 'sackedYds': 12, 'ryoe': -25.13669, 'interception': 2, 'forcedFumble': 0, 'fumbleRecovered': 0, 'defensiveTouchdown': 0, 'totalTakeaways': 2, 'weekSlug': 'WEEK_1', 'gameId': 2025090701, 'fapiGameId': 'f5919910-311e-11f0-b670-ae1250fadad1', 'opponentTeamId': '1050', 'gameResult': 'W', 'finalScore': '17-16', 'isHome': False, 'teamId': '0920', 'gp': 1, 'ppg': 16, 'ypg': 327, 'passYpg': 278, 'rushYpg': 49, 'sackedYpg': 12}, {'total': 49, 'pass': 26, 'run': 23, 'yds': 141, 'passPct': 0.53061, 'ypp': 2.87755, 'td': 2, 'passTd': 1, 'rushTd': 1, 'epa': -9.76935, 'epaPP': -0.19937, 'passYds': 95, 'passYpp': 3.65385, 'epaPass': -1.48982, 'epaPassPP': -0.0573, 'rushYds': 46, 'rushYpp': 2, 'epaRush': -8.27954, 'epaRushPP': -0.35998, 'ttt': 2.75609, 'qbp': 8, 'qbpPct': 0.28571, 'sackedYds': 18, 'ryoe': -8.1162, 'interception': 0, 'forcedFumble': 0, 'fumbleRecovered': 0, 'defensiveTouchdown': 0, 'totalTakeaways': 0, 'weekSlug': 'WEEK_1', 'gameId': 2025090701, 'fapiGameId': 'f5919910-311e-11f0-b670-ae1250fadad1', 'opponentTeamId': '0920', 'gameResult': 'L', 'finalScore': '16-17', 'isHome': True, 'teamId': '1050', 'gp': 1, 'ppg': 17, 'ypg': 141, 'passYpg': 95, 'rushYpg': 46, 'sackedYpg': 18}, {'total': 62, 'pass': 24, 'run': 38, 'yds': 302, 'passPct': 0.3871, 'ypp': 4.87097, 'td': 3, 'passTd': 0, 'rushTd': 3, 'epa': 8.64011, 'epaPP': 0.13936, 'passYds': 144, 'passYpp': 6, 'epaPass': 1.26348, 'epaPassPP': 0.05264, 'rushYds': 158, 'rushYpp': 4.15789, 'epaRush': 7.37663, 'epaRushPP': 0.19412, 'ttt': 3.17117, 'qbp': 14, 'qbpPct': 0.42424, 'sackedYds': 8, 'ryoe': 39.67451, 'interception': 0, 'forcedFumble': 0, 'fumbleRecovered': 0, 'defensiveTouchdown': 0, 'totalTakeaways': 0, 'weekSlug': 'WEEK_1', 'gameId': 2025090400, 'fapiGameId': 'f5908b6d-311e-11f0-b670-ae1250fadad1', 'opponentTeamId': '3700', 'gameResult': 'L', 'finalScore': '20-24', 'isHome': False, 'teamId': '1200', 'gp': 1, 'ppg': 24, 'ypg': 302, 'passYpg': 144, 'rushYpg': 158, 'sackedYpg': 8}, {'total': 55, 'pass': 34, 'run': 21, 'yds': 133, 'passPct': 0.61818, 'ypp': 2.41818, 'td': 0, 'passTd': 0, 'rushTd': 0, 'epa': -27.90462, 'epaPP': -0.50736, 'passYds': 62, 'passYpp': 1.82353, 'epaPass': -18.11019, 'epaPassPP': -0.53265, 'rushYds': 71, 'rushYpp': 3.38095, 'epaRush': -9.79443, 'epaRushPP': -0.4664, 'ttt': 2.89314, 'qbp': 17, 'qbpPct': 0.5, 'sackedYds': 50, 'ryoe': -1.88567, 'interception': 0, 'forcedFumble': 2, 'fumbleRecovered': 2, 'defensiveTouchdown': 0, 'totalTakeaways': 2, 'weekSlug': 'WEEK_1', 'gameId': 2025090708, 'fapiGameId': 'f61dd155-311e-11f0-b670-ae1250fadad1', 'opponentTeamId': '2100', 'gameResult': 'W', 'finalScore': '20-12', 'isHome': True, 'teamId': '1400', 'gp': 1, 'ppg': 12, 'ypg': 133, 'passYpg': 62, 'rushYpg': 71, 'sackedYpg': 50}, {'total': 47, 'pass': 22, 'run': 25, 'yds': 266, 'passPct': 0.46809, 'ypp': 5.65957, 'td': 3, 'passTd': 2, 'rushTd': 1, 'epa': 7.44871, 'epaPP': 0.15848, 'passYds': 188, 'passYpp': 8.54545, 'epaPass': 9.74849, 'epaPassPP': 0.44311, 'rushYds': 78, 'rushYpp': 3.12, 'epaRush': -2.29978, 'epaRushPP': -0.09199, 'ttt': 2.84218, 'qbp': 8, 'qbpPct': 0.34783, 'sackedYds': 0, 'ryoe': 0.4674, 'interception': 0, 'forcedFumble': 0, 'fumbleRecovered': 0, 'defensiveTouchdown': 0, 'totalTakeaways': 0, 'weekSlug': 'WEEK_1', 'gameId': 2025090710, 'fapiGameId': 'f61de295-311e-11f0-b670-ae1250fadad1', 'opponentTeamId': '1800', 'gameResult': 'L', 'finalScore': '13-27', 'isHome': False, 'teamId': '1540', 'gp': 1, 'ppg': 27, 'ypg': 266, 'passYpg': 188, 'rushYpg': 78, 'sackedYpg': 0}]}

In [8]:
fantasy_stats = nflpro_api.get_fantasy_stats(
        limit=10,
        season=2025,
        season_type=None,
        week="WEEK_1",
        positionGroup=["RB", "WR", "TE"],
        # positionGroup="QB",
        # positionGroup="SPEC",
)
if fantasy_stats:
        print("Fantasy Stats:")
        print(fantasy_stats)

# nflpro_api.stats_to_dataframe(fantasy_stats)

Fantasy Stats:

## Games

In [9]:
# nflpro_api._refresh_token()

schedule_data = nflpro_api.get_schedule(
        season=2025,
        week=3,
)
if schedule_data:
        print("Schedule:")
        print(schedule_data)

Schedule:

In [10]:
schedule_df = nflpro_api.clean_schedule_data(schedule_data)
schedule_df

,game_id_nflpro,date,time,season,season_type,week,status,datetime_ampm,home_team_id,home_team_full_name,home_team_team_id,away_team_id,away_team_fullName,away_team_teamId,venue_id,venue_name,venue_city,venue_country,game_id_elias,game_id_gsis
0,f665e5fd-311e-11f0-b670-ae1250fadad1,2025-09-19,2025-09-19T00:15:00Z,2025,REG,3,SCHEDULED,8:15 PM,10400610-c40e-a673-1743-2ce2a5d5d731,Buffalo Bills,10400610-c40e-a673-1743-2ce2a5d5d731,10402700-1662-d8ad-f45c-0b0ea460d045,Miami Dolphins,10402700-1662-d8ad-f45c-0b0ea460d045,00083770-6add-eaf7-4975-0fb66a44b335,Highmark Stadium,Orchard Park,USA,2025091800,59875
1,f665ea74-311e-11f0-b670-ae1250fadad1,2025-09-21,2025-09-21T17:00:00Z,2025,REG,3,SCHEDULED,1:00 PM,10400750-259b-33ac-eee3-a3852e83cd1f,Carolina Panthers,10400750-259b-33ac-eee3-a3852e83cd1f,10400200-f401-4e53-5175-0974e4f16cf7,Atlanta Falcons,10400200-f401-4e53-5175-0974e4f16cf7,00081769-78fe-4172-a6d6-395cf0141069,Bank of America Stadium,Charlotte,USA,2025092100,59876
2,f665eed1-311e-11f0-b670-ae1250fadad1,2025-09-21,2025-09-21T17:00:00Z,2025,REG,3,SCHEDULED,1:00 PM,10401050-5e38-b907-1be1-55b91b19c057,Cleveland Browns,10401050-5e38-b907-1be1-55b91b19c057,10401800-ab22-323d-721a-cee4713c4c2d,Green Bay Packers,10401800-ab22-323d-721a-cee4713c4c2d,00081048-4259-348c-7701-2fa3c98bcd53,Huntington Bank Field,Cleveland,USA,2025092101,59877
3,f665f386-311e-11f0-b670-ae1250fadad1,2025-09-21,2025-09-21T17:00:00Z,2025,REG,3,SCHEDULED,1:00 PM,10402250-89fe-7b86-ef98-9062cd354256,Jacksonville Jaguars,10402250-89fe-7b86-ef98-9062cd354256,10402120-b0bc-693d-098a-803014096eb0,Houston Texans,10402120-b0bc-693d-098a-803014096eb0,00082049-e1c5-6172-a084-094f2c34a377,EverBank Stadium,Jacksonville,USA,2025092102,59878
4,f665f7cb-311e-11f0-b670-ae1250fadad1,2025-09-21,2025-09-21T17:00:00Z,2025,REG,3,SCHEDULED,1:00 PM,10403000-5851-f9d5-da45-78365a05b6b0,Minnesota Vikings,10403000-5851-f9d5-da45-78365a05b6b0,10400920-57c1-7656-e77e-1af3d900483e,Cincinnati Bengals,10400920-57c1-7656-e77e-1af3d900483e,00081652-d8a8-d698-5b3f-31487c6624f7,U.S. Bank Stadium,Minneapolis,USA,2025092103,59879
5,f665fc10-311e-11f0-b670-ae1250fadad1,2025-09-21,2025-09-21T17:00:00Z,2025,REG,3,SCHEDULED,1:00 PM,10403200-69ab-9ea6-5af5-e240fbc08bea,New England Patriots,10403200-69ab-9ea6-5af5-e240fbc08bea,10403900-8251-6892-d81c-4348525c2d47,Pittsburgh Steelers,10403900-8251-6892-d81c-4348525c2d47,00081065-961a-76b2-de6a-b6da2602a129,Gillette Stadium,Foxborough,USA,2025092104,59880
6,f6660056-311e-11f0-b670-ae1250fadad1,2025-09-21,2025-09-21T17:00:00Z,2025,REG,3,SCHEDULED,1:00 PM,10403700-b939-3cbd-3d16-24d4d6742fa2,Philadelphia Eagles,10403700-b939-3cbd-3d16-24d4d6742fa2,10402510-8931-0d5f-9815-79bb79649a65,Los Angeles Rams,10402510-8931-0d5f-9815-79bb79649a65,00082769-1a91-621b-0c2d-27234c215dc0,Lincoln Financial Field,Philadelphia,USA,2025092105,59881
7,f666051f-311e-11f0-b670-ae1250fadad1,2025-09-21,2025-09-21T17:00:00Z,2025,REG,3,SCHEDULED,1:00 PM,10404900-d59e-b449-ef75-961e09ca027e,Tampa Bay Buccaneers,10404900-d59e-b449-ef75-961e09ca027e,10403430-1bc3-42c4-c7d8-39f38aed5f12,New York Jets,10403430-1bc3-42c4-c7d8-39f38aed5f12,00083697-451e-88a5-6695-aa32961fba3a,Raymond James Stadium,Tampa,USA,2025092106,59882
8,f688b03d-311e-11f0-b670-ae1250fadad1,2025-09-21,2025-09-21T17:00:00Z,2025,REG,3,SCHEDULED,1:00 PM,10402100-447f-396e-8149-0a434ffb2f23,Tennessee Titans,10402100-447f-396e-8149-0a434ffb2f23,10402200-2ea3-84c3-e627-6a6b3b39d56d,Indianapolis Colts,10402200-2ea3-84c3-e627-6a6b3b39d56d,00082350-52f3-e11f-8c49-0193cb89e66f,Nissan Stadium,Nashville,USA,2025092107,59883
9,f688baf8-311e-11f0-b670-ae1250fadad1,2025-09-21,2025-09-21T17:00:00Z,2025,REG,3,SCHEDULED,1:00 PM,10405110-ec3c-669e-2614-db3dc1736e95,Washington Commanders,10405110-ec3c-669e-2614-db3dc1736e95,10402520-96bf-e9f2-4f68-8521ca896060,Las Vegas Raiders,10402520-96bf-e9f2-4f68-8521ca896060,00082389-5f81-bc7b-7280-78260ea1be2a,Northwest Stadium,Landover,USA,2025092108,59884
10,f688bfd2-311e-11f0-b670-ae1250fadad1,2025-09-21,2025-09-21T20:05:00Z,2025,REG,3,SCHEDULED,4:05 PM,10404400-3b35-073f-197e-194bb8240723,Los Angeles Chargers,10404400-3b35-073f-197e-194bb8240723,10401400-b89b-96e5-55d1-caa7e18de3d8,Denver Broncos,10401400-b89b-96e5-55d1-caa7e18de3d8,00083005-73cf-76e4-0b7c-b1a83f72b2c5,SoFi Stadium,Inglewood,USA,2025092109,59885
11,f688c437-311e-11f0-b670-ae1250fadad1,2025-09-21,2025-09-21T20:05:00Z,2025,REG,3,SCHEDULED,4:05 PM,10404600-adcd-28ac-5826-b4d95ec2a228,Seattle Seahawks,10404600-adcd-28ac-5826-b4d95ec2a228,10403300-f235-cf9b-6d3a-2f182be48dd1,New Orleans Saints,10403300-f235-cf9b-6d3a-2f182be48dd1,00085315-d5b8-18a5-6c08-f91cd9144cb5,Lumen Field,Seattle,USA,2025092110,59886
12,f688c872-311e-11f0-b670-ae1250fadad1,2025-09-21,2025-09-21T20:25:00Z,2025,REG,3,SCHEDULED,4:25 PM,10400810-db30-43d6-221c-620006f3ca19,Chicago Bears,10400810-db30-43d6-221c-620006f3ca19,10401200-a308-98ca-ad5f-95df2fefea68,Dallas Cowboys,10401200-a308-98ca-ad5f-95df2fefea68,00084620-af4a-a315-44ad-cdc562bfc3ad,Soldier Field,Chicago,USA,2025092111,59887
13,f688ce17-311e-11f0-b670-ae1250fadad1,2025-09-21,2025-09-21T20:25:00Z,2025,REG,3,SCHEDULED,4:25 PM,10404500-e7cb-7fce-3f10-4eeb269bd179,San Francisco 49ers,10404500-e7cb-7fce-3f10-4eeb269bd179,10403800-517c-7b8c-65a3-c61b95d86123,Arizona Cardinals,10403800-517c-7b8c-65a3-c61b95d86123,00082099-57dc-7d8f-dbdb-9a693342cda6,Levi's® Stadium,Santa Clara,USA,2025092112,59888
14,f688d26d-311e-11f0-b670-ae1250fadad1,2025-09-22,2025-09-22T00:20:00Z,2025,REG,3,SCHEDULED,8:20 PM,10403410-997c-9c75-256b-3b012f468bd0,New York Giants,10403410-997c-9c75-256b-3b012f468bd0,10402310-a47e-10ea-7442-16b633633637,Kansas City Chiefs,10402310-a47e-10ea-7442-16b633633637,00083757-62dd-de21-f672-4d0ca5ad5a9e,MetLife Stadium,East Rutherford,USA,2025092113,59889
15,f688d75e-311e-11f0-b670-ae1250fadad1,2025-09-23,2025-09-23T00:15:00Z,2025,REG,3,SCHEDULED,8:15 PM,10400325-48de-3d6a-be29-8f829437f4c8,Baltimore Ravens,10400325-48de-3d6a-be29-8f829437f4c8,10401540-f97c-2d19-6fcd-fac6490a48b7,Detroit Lions,10401540-f97c-2d19-6fcd-fac6490a48b7,00083695-126e-1517-91fe-aab634a526ea,M&T Bank Stadium,Baltimore,USA,2025092200,59890

In [11]:
game_id_gsis = schedule_df["game_id_gsis"]
game_id_elias = schedule_df["game_id_elias"]
game_id_nflpro = schedule_df["game_id_nflpro"]

In [12]:
schedule_df

,game_id_nflpro,date,time,season,season_type,week,status,datetime_ampm,home_team_id,home_team_full_name,home_team_team_id,away_team_id,away_team_fullName,away_team_teamId,venue_id,venue_name,venue_city,venue_country,game_id_elias,game_id_gsis
0,f665e5fd-311e-11f0-b670-ae1250fadad1,2025-09-19,2025-09-19T00:15:00Z,2025,REG,3,SCHEDULED,8:15 PM,10400610-c40e-a673-1743-2ce2a5d5d731,Buffalo Bills,10400610-c40e-a673-1743-2ce2a5d5d731,10402700-1662-d8ad-f45c-0b0ea460d045,Miami Dolphins,10402700-1662-d8ad-f45c-0b0ea460d045,00083770-6add-eaf7-4975-0fb66a44b335,Highmark Stadium,Orchard Park,USA,2025091800,59875
1,f665ea74-311e-11f0-b670-ae1250fadad1,2025-09-21,2025-09-21T17:00:00Z,2025,REG,3,SCHEDULED,1:00 PM,10400750-259b-33ac-eee3-a3852e83cd1f,Carolina Panthers,10400750-259b-33ac-eee3-a3852e83cd1f,10400200-f401-4e53-5175-0974e4f16cf7,Atlanta Falcons,10400200-f401-4e53-5175-0974e4f16cf7,00081769-78fe-4172-a6d6-395cf0141069,Bank of America Stadium,Charlotte,USA,2025092100,59876
2,f665eed1-311e-11f0-b670-ae1250fadad1,2025-09-21,2025-09-21T17:00:00Z,2025,REG,3,SCHEDULED,1:00 PM,10401050-5e38-b907-1be1-55b91b19c057,Cleveland Browns,10401050-5e38-b907-1be1-55b91b19c057,10401800-ab22-323d-721a-cee4713c4c2d,Green Bay Packers,10401800-ab22-323d-721a-cee4713c4c2d,00081048-4259-348c-7701-2fa3c98bcd53,Huntington Bank Field,Cleveland,USA,2025092101,59877
3,f665f386-311e-11f0-b670-ae1250fadad1,2025-09-21,2025-09-21T17:00:00Z,2025,REG,3,SCHEDULED,1:00 PM,10402250-89fe-7b86-ef98-9062cd354256,Jacksonville Jaguars,10402250-89fe-7b86-ef98-9062cd354256,10402120-b0bc-693d-098a-803014096eb0,Houston Texans,10402120-b0bc-693d-098a-803014096eb0,00082049-e1c5-6172-a084-094f2c34a377,EverBank Stadium,Jacksonville,USA,2025092102,59878
4,f665f7cb-311e-11f0-b670-ae1250fadad1,2025-09-21,2025-09-21T17:00:00Z,2025,REG,3,SCHEDULED,1:00 PM,10403000-5851-f9d5-da45-78365a05b6b0,Minnesota Vikings,10403000-5851-f9d5-da45-78365a05b6b0,10400920-57c1-7656-e77e-1af3d900483e,Cincinnati Bengals,10400920-57c1-7656-e77e-1af3d900483e,00081652-d8a8-d698-5b3f-31487c6624f7,U.S. Bank Stadium,Minneapolis,USA,2025092103,59879
5,f665fc10-311e-11f0-b670-ae1250fadad1,2025-09-21,2025-09-21T17:00:00Z,2025,REG,3,SCHEDULED,1:00 PM,10403200-69ab-9ea6-5af5-e240fbc08bea,New England Patriots,10403200-69ab-9ea6-5af5-e240fbc08bea,10403900-8251-6892-d81c-4348525c2d47,Pittsburgh Steelers,10403900-8251-6892-d81c-4348525c2d47,00081065-961a-76b2-de6a-b6da2602a129,Gillette Stadium,Foxborough,USA,2025092104,59880
6,f6660056-311e-11f0-b670-ae1250fadad1,2025-09-21,2025-09-21T17:00:00Z,2025,REG,3,SCHEDULED,1:00 PM,10403700-b939-3cbd-3d16-24d4d6742fa2,Philadelphia Eagles,10403700-b939-3cbd-3d16-24d4d6742fa2,10402510-8931-0d5f-9815-79bb79649a65,Los Angeles Rams,10402510-8931-0d5f-9815-79bb79649a65,00082769-1a91-621b-0c2d-27234c215dc0,Lincoln Financial Field,Philadelphia,USA,2025092105,59881
7,f666051f-311e-11f0-b670-ae1250fadad1,2025-09-21,2025-09-21T17:00:00Z,2025,REG,3,SCHEDULED,1:00 PM,10404900-d59e-b449-ef75-961e09ca027e,Tampa Bay Buccaneers,10404900-d59e-b449-ef75-961e09ca027e,10403430-1bc3-42c4-c7d8-39f38aed5f12,New York Jets,10403430-1bc3-42c4-c7d8-39f38aed5f12,00083697-451e-88a5-6695-aa32961fba3a,Raymond James Stadium,Tampa,USA,2025092106,59882
8,f688b03d-311e-11f0-b670-ae1250fadad1,2025-09-21,2025-09-21T17:00:00Z,2025,REG,3,SCHEDULED,1:00 PM,10402100-447f-396e-8149-0a434ffb2f23,Tennessee Titans,10402100-447f-396e-8149-0a434ffb2f23,10402200-2ea3-84c3-e627-6a6b3b39d56d,Indianapolis Colts,10402200-2ea3-84c3-e627-6a6b3b39d56d,00082350-52f3-e11f-8c49-0193cb89e66f,Nissan Stadium,Nashville,USA,2025092107,59883
9,f688baf8-311e-11f0-b670-ae1250fadad1,2025-09-21,2025-09-21T17:00:00Z,2025,REG,3,SCHEDULED,1:00 PM,10405110-ec3c-669e-2614-db3dc1736e95,Washington Commanders,10405110-ec3c-669e-2614-db3dc1736e95,10402520-96bf-e9f2-4f68-8521ca896060,Las Vegas Raiders,10402520-96bf-e9f2-4f68-8521ca896060,00082389-5f81-bc7b-7280-78260ea1be2a,Northwest Stadium,Landover,USA,2025092108,59884
10,f688bfd2-311e-11f0-b670-ae1250fadad1,2025-09-21,2025-09-21T20:05:00Z,2025,REG,3,SCHEDULED,4:05 PM,10404400-3b35-073f-197e-194bb8240723,Los Angeles Chargers,10404400-3b35-073f-197e-194bb8240723,10401400-b89b-96e5-55d1-caa7e18de3d8,Denver Broncos,10401400-b89b-96e5-55d1-caa7e18de3d8,00083005-73cf-76e4-0b7c-b1a83f72b2c5,SoFi Stadium,Inglewood,USA,2025092109,59885
11,f688c437-311e-11f0-b670-ae1250fadad1,2025-09-21,2025-09-21T20:05:00Z,2025,REG,3,SCHEDULED,4:05 PM,10404600-adcd-28ac-5826-b4d95ec2a228,Seattle Seahawks,10404600-adcd-28ac-5826-b4d95ec2a228,10403300-f235-cf9b-6d3a-2f182be48dd1,New Orleans Saints,10403300-f235-cf9b-6d3a-2f182be48dd1,00085315-d5b8-18a5-6c08-f91cd9144cb5,Lumen Field,Seattle,USA,2025092110,59886
12,f688c872-311e-11f0-b670-ae1250fadad1,2025-09-21,2025-09-21T20:25:00Z,2025,REG,3,SCHEDULED,4:25 PM,10400810-db30-43d6-221c-620006f3ca19,Chicago Bears,10400810-db30-43d6-221c-620006f3ca19,10401200-a308-98ca-ad5f-95df2fefea68,Dallas Cowboys,10401200-a308-98ca-ad5f-95df2fefea68,00084620-af4a-a315-44ad-cdc562bfc3ad,Soldier Field,Chicago,USA,2025092111,59887
13,f688ce17-311e-11f0-b670-ae1250fadad1,2025-09-21,2025-09-21T20:25:00Z,2025,REG,3,SCHEDULED,4:25 PM,10404500-e7cb-7fce-3f10-4eeb269bd179,San Francisco 49ers,10404500-e7cb-7fce-3f10-4eeb269bd179,10403800-517c-7b8c-65a3-c61b95d86123,Arizona Cardinals,10403800-517c-7b8c-65a3-c61b95d86123,00082099-57dc-7d8f-dbdb-9a693342cda6,Levi's® Stadium,Santa Clara,USA,2025092112,59888
14,f688d26d-311e-11f0-b670-ae1250fadad1,2025-09-22,2025-09-22T00:20:00Z,2025,REG,3,SCHEDULED,8:20 PM,10403410-997c-9c75-256b-3b012f468bd0,New York Giants,10403410-997c-9c75-256b-3b012f468bd0,10402310-a47e-10ea-7442-16b633633637,Kansas City Chiefs,10402310-a47e-10ea-7442-16b633633637,00083757-62dd-de21-f672-4d0ca5ad5a9e,MetLife Stadium,East Rutherford,USA,2025092113,59889
15,f688d75e-311e-11f0-b670-ae1250fadad1,2025-09-23,2025-09-23T00:15:00Z,2025,REG,3,SCHEDULED,8:15 PM,10400325-48de-3d6a-be29-8f829437f4c8,Baltimore Ravens,10400325-48de-3d6a-be29-8f829437f4c8,10401540-f97c-2d19-6fcd-fac6490a48b7,Detroit Lions,10401540-f97c-2d19-6fcd-fac6490a48b7,00083695-126e-1517-91fe-aab634a526ea,M&T Bank Stadium,Baltimore,USA,2025092200,59890

In [13]:
for g in game_id_elias[[6]]:
        print(g)

        pbp_data = nflpro_api.get_play_by_play_stats(
                game_id=g
        )
        if pbp_data:
                print("Play-by-Play:")
                print(pbp_data)

        pbp_df = nflpro_api.stats_to_dataframe(pbp_data)

pbp_df

2025092105
Play-by-Play:

AttributeError: 'list' object has no attribute 'get'

In [41]:
import pandas as pd

data_list = pbp_data["plays"]

important_cols = []
unnest_cols = ["playStats", "unofficialPlay", "nflIds", "offense", "defense", "passInfo", "recInfo"]

if not data_list:
    pd.DataFrame()

formatted_df = pd.DataFrame(data_list)

for col in unnest_cols:
        if col in formatted_df.columns:
            # Handle lists by extracting the first element if it exists
            formatted_df[col] = formatted_df[col.apply(
                lambda x: x[0] if isinstance(x, list) and len(x) > 0 else x
            )]

            # Normalize only if the column contains dictionaries after list handling
            if formatted_df[col].apply(lambda x: isinstance(x, dict)).any():
                formatted_df = formatted_df.join(
                    pd.json_normalize(formatted_df[col]).add_prefix(f"{col}_"),
                    rsuffix=f"_{col}",
                ).drop(col, axis=1)
            else:
                print(f"Skipping json_normalize for {col} as it does not contain dictionaries.")

remaining_cols = [
    col for col in formatted_df.columns if col not in important_cols
]
ordered_cols = [
    col for col in important_cols if col in formatted_df.columns
] + remaining_cols

formatted_df[ordered_cols]

AttributeError: 'str' object has no attribute 'apply'

In [24]:
plays_list = pbp_data.get(
    "plays",
    [],
)  # Access the list of play dictionaries

plays_data = []  # Initialize an empty list to hold the data

for play in plays_list:
    row = {
        "gameId": play["gameId"],
        "playId": play["playId"],
        "playDescription": play["playDescription"],
        "possessionTeam": play["possessionTeam"],
        "down": play["down"],
        "yardsToGo": play["yardsToGo"],
        "quarter": play["quarter"],
    }

    plays_data.append(row)

plays_data

[{'gameId': 2025092105,
  'playId': 1,
  'playDescription': 'GAME',
  'possessionTeam': '',
  'down': 0,
  'yardsToGo': 0,
  'quarter': 1},
 {'gameId': 2025092105,
  'playId': 40,
  'playDescription': 'J.Elliott kicks 64 yards from PHI 35 to LA 1. B.Corum to LA 23 for 22 yards (J.Trotter; K.Granson).',
  'possessionTeam': 'PHI',
  'down': 0,
  'yardsToGo': 0,
  'quarter': 1},
 {'gameId': 2025092105,
  'playId': 63,
  'playDescription': '(14:54) K.Williams up the middle to LA 28 for 5 yards (J.Davis).',
  'possessionTeam': 'LAR',
  'down': 1,
  'yardsToGo': 10,
  'quarter': 1},
 {'gameId': 2025092105,
  'playId': 85,
  'playDescription': '(14:20) M.Stafford pass short right to K.Williams to LA 36 for 8 yards (C.DeJean) [N.Smith].',
  'possessionTeam': 'LAR',
  'down': 2,
  'yardsToGo': 5,
  'quarter': 1},
 {'gameId': 2025092105,
  'playId': 110,
  'playDescription': '(13:37) (Shotgun) M.Stafford pass incomplete short left to K.Williams.',
  'possessionTeam': 'LAR',
  'down': 1,
  'yardsToGo': 10,
  'quarter': 1},
 {'gameId': 2025092105,
  'playId': 133,
  'playDescription': '(13:32) (No Huddle, Shotgun) M.Stafford pass short middle intended for D.Adams INTERCEPTED by Z.Baun at LA 38. Z.Baun to LA 38 for no gain (D.Adams).',
  'possessionTeam': 'LAR',
  'down': 2,
  'yardsToGo': 10,
  'quarter': 1},
 {'gameId': 2025092105,
  'playId': 160,
  'playDescription': '(13:28) (Shotgun) S.Barkley right guard to LA 37 for 1 yard (K.Turner; J.Verse).',
  'possessionTeam': 'PHI',
  'down': 1,
  'yardsToGo': 10,
  'quarter': 1},
 {'gameId': 2025092105,
  'playId': 182,
  'playDescription': '(12:46) (Shotgun) J.Hurts pass short right to D.Smith to LA 32 for 5 yards (K.Kinchens; E.Forbes).',
  'possessionTeam': 'PHI',
  'down': 2,
  'yardsToGo': 9,
  'quarter': 1},
 {'gameId': 2025092105,
  'playId': 207,
  'playDescription': '(12:03) (Shotgun) J.Hurts scrambles up the middle to LA 30 for 2 yards (O.Speights).',
  'possessionTeam': 'PHI',
  'down': 3,
  'yardsToGo': 4,
  'quarter': 1},
 {'gameId': 2025092105,
  'playId': 229,
  'playDescription': '(11:16) (Shotgun) J.Hurts right end ran ob at LA 12 for 18 yards (K.Curl).',
  'possessionTeam': 'PHI',
  'down': 4,
  'yardsToGo': 2,
  'quarter': 1},
 {'gameId': 2025092105,
  'playId': 256,
  'playDescription': '(10:36) (Shotgun) S.Barkley up the middle to LA 14 for -2 yards (J.Verse, Q.Lake).',
  'possessionTeam': 'PHI',
  'down': 1,
  'yardsToGo': 10,
  'quarter': 1},
 {'gameId': 2025092105,
  'playId': 278,
  'playDescription': '(9:53) (Shotgun) J.Hurts pass incomplete short left to J.Dotson.',
  'possessionTeam': 'PHI',
  'down': 2,
  'yardsToGo': 12,
  'quarter': 1},
 {'gameId': 2025092105,
  'playId': 301,
  'playDescription': '(9:49) (Shotgun) J.Hurts pass short right to D.Smith to LA 3 for 11 yards (K.Curl, E.Forbes).',
  'possessionTeam': 'PHI',
  'down': 3,
  'yardsToGo': 12,
  'quarter': 1},
 {'gameId': 2025092105,
  'playId': 326,
  'playDescription': '(9:08) J.Hurts up the middle to LA 2 for 1 yard (N.Landman; J.Verse).',
  'possessionTeam': 'PHI',
  'down': 4,
  'yardsToGo': 1,
  'quarter': 1},
 {'gameId': 2025092105,
  'playId': 348,
  'playDescription': '(8:16) J.Hurts pass incomplete short middle to A.Brown.\r\nPENALTY on LA-Q.Lake, Defensive Pass Interference, 1 yard, enforced at LA 2 - No Play.',
  'possessionTeam': 'PHI',
  'down': 1,
  'yardsToGo': 2,
  'quarter': 1},
 {'gameId': 2025092105,
  'playId': 382,
  'playDescription': '(8:12) J.Hurts up the middle for 1 yard, TOUCHDOWN.',
  'possessionTeam': 'PHI',
  'down': 1,
  'yardsToGo': 1,
  'quarter': 1},
 {'gameId': 2025092105,
  'playId': 405,
  'playDescription': 'J.Elliott extra point is GOOD, Center-C.Hughlett, Holder-B.Mann.',
  'possessionTeam': 'PHI',
  'down': 0,
  'yardsToGo': 0,
  'quarter': 1},
 {'gameId': 2025092105,
  'playId': 430,
  'playDescription': 'Timeout at 08:07.',
  'possessionTeam': '',
  'down': 0,
  'yardsToGo': 0,
  'quarter': 1},
 {'gameId': 2025092105,
  'playId': 420,
  'playDescription': 'J.Elliott kicks 61 yards from PHI 35 to LA 4. B.Corum to LA 30 for 26 yards (K.Ringo).',
  'possessionTeam': 'PHI',
  'down': 0,
  'yardsToGo': 0,
  'quarter': 1},
 {'gameId': 2025092105,
  'playId': 450,
  'playDescription': '(8:01) K.Williams right tackle to LA 36 for 6 yards (J.Davis).',
  'possessionTeam': 'LAR',
  'down': 1,
  'yardsToGo': 10,
  'quarter': 1},
 {'gameId': 2025092105,
  'playId': 472,
  'playDescription': '(7:28) K.Williams right guard to LA 41 for 5 yards (J.Campbell).',
  'possessionTeam': 'LAR',
  'down': 2,
  'yardsToGo': 4,
  'quarter': 1},
 {'gameId': 2025092105,
  'playId': 494,
  'playDescription': '(6:53) K.Williams right end to PHI 48 for 11 yards (J.Campbell).',
  'possessionTeam': 'LAR',
  'down': 1,
  'yardsToGo': 10,
  'quarter': 1},
 {'gameId': 2025092105,
  'playId': 516,
  'playDescription': '(6:16) B.Corum right tackle to PHI 48 for no gain (N.Smith).',
  'possessionTeam': 'LAR',
  'down': 1,
  'yardsToGo': 10,
  'quarter': 1},
 {'gameId': 2025092105,
  'playId': 538,
  'playDescription': '(5:39) M.Stafford pass short right to P.Nacua to PHI 37 for 11 yards (C.DeJean; J.Campbell).',
  'possessionTeam': 'LAR',
  'down': 2,
  'yardsToGo': 10,
  'quarter': 1},
 {'gameId': 2025092105,
  'playId': 563,
  'playDescription': '(4:57) M.Stafford pass incomplete short left to J.Whittington [J.Hunt].',
  'possessionTeam': 'LAR',
  'down': 1,
  'yardsToGo': 10,
  'quarter': 1},
 {'gameId': 2025092105,
  'playId': 586,
  'playDescription': '(4:53) (Shotgun) M.Stafford pass short middle to P.Nacua to PHI 33 for 4 yards (Z.Baun).',
  'possessionTeam': 'LAR',
  'down': 2,
  'yardsToGo': 10,
  'quarter': 1},
 {'gameId': 2025092105,
  'playId': 611,
  'playDescription': '(4:09) (Shotgun) M.Stafford pass incomplete short middle to T.Atwell (Z.Baun).',
  'possessionTeam': 'LAR',
  'down': 3,
  'yardsToGo': 6,
  'quarter': 1},
 {'gameId': 2025092105,
  'playId': 634,
  'playDescription': '(4:05) J.Karty 51 yard field goal is GOOD, Center-A.Ward, Holder-E.Evans.',
  'possessionTeam': 'LAR',
  'down': 4,
  'yardsToGo': 6,
  'quarter': 1},
 {'gameId': 2025092105,
  'playId': 664,
  'playDescription': 'Timeout at 04:00.',
  'possessionTeam': '',
  'down': 0,
  'yardsToGo': 0,
  'quarter': 1},
 {'gameId': 2025092105,
  'playId': 654,
  'playDescription': 'J.Karty kicks 65 yards from LA 35 to landing zone to end zone, Touchback to the PHI 20.',
  'possessionTeam': 'LAR',
  'down': 0,
  'yardsToGo': 0,
  'quarter': 1},
 {'gameId': 2025092105,
  'playId': 690,
  'playDescription': '(3:55) (Shotgun) J.Hurts pass incomplete short right.',
  'possessionTeam': 'PHI',
  'down': 1,
  'yardsToGo': 10,
  'quarter': 1},
 {'gameId': 2025092105,
  'playId': 717,
  'playDescription': '(3:47) (Shotgun) J.Hurts sacked at PHI 12 for -8 yards (P.Ford).',
  'possessionTeam': 'PHI',
  'down': 2,
  'yardsToGo': 10,
  'quarter': 1},
 {'gameId': 2025092105,
  'playId': 737,
  'playDescription': '(3:05) (Shotgun) S.Barkley up the middle to PHI 15 for 3 yards (K.Curl).',
  'possessionTeam': 'PHI',
  'down': 3,
  'yardsToGo': 18,
  'quarter': 1},
 {'gameId': 2025092105,
  'playId': 759,
  'playDescription': '(2:29) B.Mann punts 59 yards to LA 26, Center-C.Hughlett. X.Smith to LA 46 for 20 yards (J.Trotter).',
  'possessionTeam': 'PHI',
  'down': 4,
  'yardsToGo': 15,
  'quarter': 1},
 {'gameId': 2025092105,
  'playId': 797,
  'playDescription': 'Timeout at 02:15.',
  'possessionTeam': '',
  'down': 0,
  'yardsToGo': 0,
  'quarter': 1},
 {'gameId': 2025092105,
  'playId': 804,
  'playDescription': '** Injury Update: PHI-L.Johnson return is Questionable.',
  'possessionTeam': '',
  'down': 0,
  'yardsToGo': 0,
  'quarter': 1},
 {'gameId': 2025092105,
  'playId': 785,
  'playDescription': '(2:15) M.Stafford pass incomplete short right to T.Higbee.',
  'possessionTeam': 'LAR',
  'down': 1,
  'yardsToGo': 10,
  'quarter': 1},
 {'gameId': 2025092105,
  'playId': 820,
  'playDescription': '(2:11) B.Corum left end to PHI 44 for 10 yards (Z.Baun; A.Mukuba).',
  'possessionTeam': 'LAR',
  'down': 2,
  'yardsToGo': 10,
  'quarter': 1},
 {'gameId': 2025092105,
  'playId': 842,
  'playDescription': '(1:28) M.Stafford pass deep left to D.Adams for 44 yards, TOUCHDOWN.',
  'possessionTeam': 'LAR',
  'down': 1,
  'yardsToGo': 10,
  'quarter': 1},
 {'gameId': 2025092105,
  'playId': 873,
  'playDescription': 'J.Karty extra point is GOOD, Center-A.Ward, Holder-E.Evans.',
  'possessionTeam': 'LAR',
  'down': 0,
  'yardsToGo': 0,
  'quarter': 1},
 {'gameId': 2025092105,
  'playId': 898,
  'playDescription': 'Timeout at 01:20.',
  'possessionTeam': '',
  'down': 0,
  'yardsToGo': 0,
  'quarter': 1},
 {'gameId': 2025092105,
  'playId': 888,
  'playDescription': 'J.Karty kicks 62 yards from LA 35 to PHI 3. T.Bigsby pushed ob at PHI 19 for 16 yards (T.Reeder).',
  'possessionTeam': 'LAR',
  'down': 0,
  'yardsToGo': 0,
  'quarter': 1},
 {'gameId': 2025092105,
  'playId': 921,
  'playDescription': '(1:17) J.Hurts pass incomplete short middle to A.Brown (Q.Lake).',
  'possessionTeam': 'PHI',
  'down': 1,
  'yardsToGo': 10,
  'quarter': 1},
 {'gameId': 2025092105,
  'playId': 944,
  'playDescription': '(1:12) (Shotgun) S.Barkley right guard to PHI 21 for 2 yards (B.Fiske; T.Davis).',
  'possessionTeam': 'PHI',
  'down': 2,
  'yardsToGo': 10,
  'quarter': 1},
 {'gameId': 2025092105,
  'playId': 966,
  'playDescription': '(:36) (Shotgun) J.Hurts sacked at PHI 11 for -10 yards (J.McCollough).',
  'possessionTeam': 'PHI',
  'down': 3,
  'yardsToGo': 8,
  'quarter': 1},
 {'gameId': 2025092105,
  'playId': 991,
  'playDescription': 'END QUARTER 1',
  'possessionTeam': '',
  'down': 0,
  'yardsToGo': 0,
  'quarter': 1},
 {'gameId': 2025092105,
  'playId': 1015,
  'playDescription': '(15:00) B.Mann punts 64 yards to LA 25, Center-C.Hughlett. X.Smith to LA 34 for 9 yards (G.Calcaterra).\r\nPenalty on LA-J.McCollough, Offensive Holding, offsetting, enforced at LA 34.\r\nPenalty on PHI-S.Brown, Unnecessary Roughness, offsetting.',
  'possessionTeam': 'PHI',
  'down': 4,
  'yardsToGo': 18,
  'quarter': 2},
 {'gameId': 2025092105,
  'playId': 1052,
  'playDescription': '(14:49) K.Williams right end pushed ob at LA 47 for 13 yards (J.Campbell).',
  'possessionTeam': 'LAR',
  'down': 1,
  'yardsToGo': 10,
  'quarter': 2},
 {'gameId': 2025092105,
  'playId': 1079,
  'playDescription': '(14:14) K.Williams right guard to LA 47 for no gain (Z.Baun).',
  'possessionTeam': 'LAR',
  'down': 1,
  'yardsToGo': 10,
  'quarter': 2},
 {'gameId': 2025092105,
  'playId': 1101,
  'playDescription': '(13:33) (Shotgun) M.Stafford pass short right to P.Nacua to 50 for 3 yards (A.Jackson).',
  'possessionTeam': 'LAR',
  'down': 2,
  'yardsToGo': 10,
  'quarter': 2},
 {'gameId': 2025092105,
  'playId': 1126,
  'playDescription': '(13:03) (Shotgun) M.Stafford pass incomplete deep right to D.Adams.\r\nPENALTY on PHI-Q.Mitchell, Defensive Pass Interference, 17 yards, enforced at 50 - No Play.',
  'possessionTeam': 'LAR',
  'down': 3,
  'yardsToGo': 7,
  'quarter': 2},
 {'gameId': 2025092105,
  'playId': 1160,
  'playDescription': '(12:59) K.Williams left guard to PHI 30 for 3 yards (M.Ojomo).',
  'possessionTeam': 'LAR',
  'down': 1,
  'yardsToGo': 10,
  'quarter': 2},
 {'gameId': 2025092105,
  'playId': 1182,
  'playDescription': '(12:18) K.Williams up the middle to PHI 23 for 7 yards (J.Campbell; C.DeJean).',
  'possessionTeam': 'LAR',
  'down': 2,
  'yardsToGo': 7,
  'quarter': 2},
 {'gameId': 2025092105,
  'playId': 1204,
  'playDescription': '(11:32) B.Corum left tackle to PHI 16 for 7 yards (S.Brown).',
  'possessionTeam': 'LAR',
  'down': 1,
  'yardsToGo': 10,
  'quarter': 2},
 {'gameId': 2025092105,
  'playId': 1226,
  'playDescription': '(10:51) B.Corum left tackle to PHI 6 for 10 yards (R.Blankenship; Q.Mitchell).',
  'possessionTeam': 'LAR',
  'down': 2,
  'yardsToGo': 3,
  'quarter': 2},
 {'gameId': 2025092105,
  'playId': 1248,
  'playDescription': '(10:12) M.Stafford pass incomplete short left to D.Adams.',
  'possessionTeam': 'LAR',
  'down': 1,
  'yardsToGo': 6,
  'quarter': 2},
 {'gameId': 2025092105,
  'playId': 1271,
  'playDescription': '(10:09) K.Williams right tackle to PHI 2 for 4 yards (A.Jackson; A.Mukuba).',
  'possessionTeam': 'LAR',
  'down': 2,
  'yardsToGo': 6,
  'quarter': 2},
 {'gameId': 2025092105,
  'playId': 1293,
  'playDescription': '(9:30) K.Williams right guard for 2 yards, TOUCHDOWN NULLIFIED by Penalty.\r\nPENALTY on LA-C.Shelton, Offensive Holding, 10 yards, enforced at PHI 0.',
  'possessionTeam': 'LAR',
  'down': 3,
  'yardsToGo': 2,
  'quarter': 2},
 {'gameId': 2025092105,
  'playId': 1327,
  'playDescription': '(9:25) (Shotgun) M.Stafford pass incomplete short left to T.Higbee.',
  'possessionTeam': 'LAR',
  'down': 3,
  'yardsToGo': 10,
  'quarter': 2},
 {'gameId': 2025092105,
  'playId': 1352,
  'playDescription': '(9:18) J.Karty 28 yard field goal is GOOD, Center-A.Ward, Holder-E.Evans.',
  'possessionTeam': 'LAR',
  'down': 4,
  'yardsToGo': 10,
  'quarter': 2},
 {'gameId': 2025092105,
  'playId': 1388,
  'playDescription': 'Timeout at 09:15.',
  'possessionTeam': '',
  'down': 0,
  'yardsToGo': 0,
  'quarter': 2},
 {'gameId': 2025092105,
  'playId': 1378,
  'playDescription': 'J.Karty kicks 58 yards from LA 35 to PHI 7. J.Metchie MUFFS catch, and recovers at PHI 6. J.Metchie to PHI 27 for 21 yards (O.Speights).\r\nPENALTY on PHI-J.Trotter, Illegal Block Above the Waist, 8 yards, enforced at PHI 17.\r\nPenalty on PHI-G.Calcaterra, Offensive Holding, declined.',
  'possessionTeam': 'LAR',
  'down': 0,
  'yardsToGo': 0,
  'quarter': 2},
 {'gameId': 2025092105,
  'playId': 1426,
  'playDescription': '(9:08) S.Barkley right guard to PHI 10 for 1 yard (K.Curl; P.Ford).',
  'possessionTeam': 'PHI',
  'down': 1,
  'yardsToGo': 10,
  'quarter': 2},
 {'gameId': 2025092105,
  'playId': 1448,
  'playDescription': '(8:38) (No Huddle, Shotgun) J.Hurts pass short left to S.Barkley pushed ob at PHI 12 for 2 yards (Q.Lake; K.Curl).',
  'possessionTeam': 'PHI',
  'down': 2,
  'yardsToGo': 9,
  'quarter': 2},
 {'gameId': 2025092105,
  'playId': 1489,
  'playDescription': '(8:01) (Shotgun) J.Hurts pass incomplete deep right to J.Dotson (Q.Lake).',
  'possessionTeam': 'PHI',
  'down': 3,
  'yardsToGo': 7,
  'quarter': 2},
 {'gameId': 2025092105,
  'playId': 1512,
  'playDescription': '(7:55) B.Mann punts 57 yards to LA 31, Center-C.Hughlett. X.Smith to LA 46 for 15 yards (J.Trotter).',
  'possessionTeam': 'PHI',
  'down': 4,
  'yardsToGo': 7,
  'quarter': 2},
 {'gameId': 2025092105,
  'playId': 1550,
  'playDescription': 'Timeout at 07:44.',
  'possessionTeam': '',
  'down': 0,
  'yardsToGo': 0,
  'quarter': 2},
 {'gameId': 2025092105,
  'playId': 1538,
  'playDescription': '(7:44) B.Corum right guard to 50 for 4 yards (A.Jackson; B.Young).',
  'possessionTeam': 'LAR',
  'down': 1,
  'yardsToGo': 10,
  'quarter': 2},
 {'gameId': 2025092105,
  'playId': 1567,
  'playDescription': '(7:04) M.Stafford pass short right to P.Nacua to PHI 35 for 15 yards (C.DeJean).',
  'possessionTeam': 'LAR',
  'down': 2,
  'yardsToGo': 6,
  'quarter': 2},
 {'gameId': 2025092105,
  'playId': 1592,
  'playDescription': '(6:23) (Shotgun) M.Stafford pass short right to D.Adams ran ob at PHI 31 for 4 yards (Q.Mitchell).',
  'possessionTeam': 'LAR',
  'down': 1,
  'yardsToGo': 10,
  'quarter': 2},
 {'gameId': 2025092105,
  'playId': 1622,
  'playDescription': '(5:47) B.Corum left end pushed ob at PHI 22 for 9 yards (A.Jackson).',
  'possessionTeam': 'LAR',
  'down': 2,
  'yardsToGo': 6,
  'quarter': 2},
 {'gameId': 2025092105,
  'playId': 1649,
  'playDescription': '(5:12) J.Whittington left end to PHI 16 for 6 yards (R.Blankenship).',
  'possessionTeam': 'LAR',
  'down': 1,
  'yardsToGo': 10,
  'quarter': 2},
 {'gameId': 2025092105,
  'playId': 1671,
  'playDescription': '(4:30) K.Williams up the middle to PHI 15 for 1 yard (J.Carter; S.Brown).',
  'possessionTeam': 'LAR',
  'down': 2,
  'yardsToGo': 4,
  'quarter': 2},
 {'gameId': 2025092105,
  'playId': 1693,
  'playDescription': '(3:49) (Shotgun) M.Stafford pass incomplete short left to D.Adams.',
  'possessionTeam': 'LAR',
  'down': 3,
  'yardsToGo': 3,
  'quarter': 2},
 {'gameId': 2025092105,
  'playId': 1716,
  'playDescription': '(3:46) J.Karty 33 yard field goal is GOOD, Center-A.Ward, Holder-E.Evans.',
  'possessionTeam': 'LAR',
  'down': 4,
  'yardsToGo': 3,
  'quarter': 2},
 {'gameId': 2025092105,
  'playId': 1746,
  'playDescription': 'Timeout at 03:43.',
  'possessionTeam': '',
  'down': 0,
  'yardsToGo': 0,
  'quarter': 2},
 {'gameId': 2025092105,
  'playId': 1736,
  'playDescription': 'J.Karty kicks 53 yards from LA 35 to PHI 12. T.Bigsby MUFFS catch, and recovers at PHI 6. T.Bigsby to PHI 14 for 8 yards (X.Smith; S.Dolac).',
  'possessionTeam': 'LAR',
  'down': 0,
  'yardsToGo': 0,
  'quarter': 2},
 {'gameId': 2025092105,
  'playId': 1771,
  'playDescription': '(3:36) J.Hurts pass short right to S.Barkley to PHI 13 for -1 yards (B.Young).\r\nPENALTY on PHI-A.Brown, Unnecessary Roughness, 6 yards, enforced at PHI 13.',
  'possessionTeam': 'PHI',
  'down': 1,
  'yardsToGo': 10,
  'quarter': 2},
 {'gameId': 2025092105,
  'playId': 1820,
  'playDescription': '(3:22) S.Barkley up the middle to PHI 8 for 1 yard (J.Verse).',
  'possessionTeam': 'PHI',
  'down': 2,
  'yardsToGo': 17,
  'quarter': 2},
 {'gameId': 2025092105,
  'playId': 1842,
  'playDescription': '(2:36) (Shotgun) S.Barkley left guard to PHI 15 for 7 yards (N.Landman).',
  'possessionTeam': 'PHI',
  'down': 3,
  'yardsToGo': 16,
  'quarter': 2},
 {'gameId': 2025092105,
  'playId': 1876,
  'playDescription': 'Two-Minute Warning',
  'possessionTeam': '',
  'down': 0,
  'yardsToGo': 0,
  'quarter': 2},
 {'gameId': 2025092105,
  'playId': 1864,
  'playDescription': '(2:00) B.Mann punts 42 yards to LA 43, Center-C.Hughlett. X.Smith to PHI 48 for 9 yards (M.Epps).',
  'possessionTeam': 'PHI',
  'down': 4,
  'yardsToGo': 9,
  'quarter': 2},
 {'gameId': 2025092105,
  'playId': 1905,
  'playDescription': '(1:52) K.Williams left guard to PHI 36 for 12 yards (C.DeJean).',
  'possessionTeam': 'LAR',
  'down': 1,
  'yardsToGo': 10,
  'quarter': 2},
 {'gameId': 2025092105,
  'playId': 1933,
  'playDescription': '(1:27) (No Huddle, Shotgun) M.Stafford pass short left to D.Adams to PHI 28 for 8 yards (Q.Mitchell).',
  'possessionTeam': 'LAR',
  'down': 1,
  'yardsToGo': 10,
  'quarter': 2},
 {'gameId': 2025092105,
  'playId': 1958,
  'playDescription': '(:57) K.Williams left guard to PHI 28 for no gain (Z.Baun).',
  'possessionTeam': 'LAR',
  'down': 2,
  'yardsToGo': 2,
  'quarter': 2},
 {'gameId': 2025092105,
  'playId': 1980,
  'playDescription': '(:19) M.Stafford pass incomplete short left to P.Nacua.',
  'possessionTeam': 'LAR',
  'down': 3,
  'yardsToGo': 2,
  'quarter': 2},
 {'gameId': 2025092105,
  'playId': 2003,
  'playDescription': '(:14) J.Karty 46 yard field goal is GOOD, Center-A.Ward, Holder-E.Evans.',
  'possessionTeam': 'LAR',
  'down': 4,
  'yardsToGo': 2,
  'quarter': 2},
 {'gameId': 2025092105,
  'playId': 2033,
  'playDescription': 'Timeout at 00:10.',
  'possessionTeam': '',
  'down': 0,
  'yardsToGo': 0,
  'quarter': 2},
 {'gameId': 2025092105,
  'playId': 2023,
  'playDescription': 'E.Evans kicks 65 yards from LA 35 to end zone, Touchback to the PHI 35.',
  'possessionTeam': 'LAR',
  'down': 0,
  'yardsToGo': 0,
  'quarter': 2},
 {'gameId': 2025092105,
  'playId': 2047,
  'playDescription': '(:10) J.Hurts kneels to PHI 34 for -1 yards.',
  'possessionTeam': 'PHI',
  'down': 1,
  'yardsToGo': 10,
  'quarter': 2},
 {'gameId': 2025092105,
  'playId': 2069,
  'playDescription': 'END QUARTER 2',
  'possessionTeam': '',
  'down': 0,
  'yardsToGo': 0,
  'quarter': 2},
 {'gameId': 2025092105,
  'playId': 2089,
  'playDescription': 'J.Karty kicks 61 yards from LA 35 to PHI 4. J.Metchie MUFFS catch, and recovers at PHI 3. J.Metchie to PHI 10 for 7 yards (K.Kinchens).',
  'possessionTeam': 'LAR',
  'down': 0,
  'yardsToGo': 0,
  'quarter': 3},

In [20]:
print(game_id_elias[6])
print(schedule_df["game_id_nflpro"][6])
print(pbp_df["playId"][190])


g = schedule_df["game_id_nflpro"][6]
p = pbp_df["playId"][190]

coaches_data = nflpro_api.get_coaches(
        gameId=g,
        playId=p,
)
if coaches_data:
        print("Coaches:")
        print(coaches_data)

2025092105
f6660056-311e-11f0-b670-ae1250fadad1
4358
Coaches:
{'items': [{'type': 'video', 'language': None, 'advertiserId': None, 'author': None, 'authorizations': {'nfl_plus_premium': [{'NFL PLUS - COACHES FILM': {'requirements': {'countryCode': ['US']}}}], 'pro_premium': [{'NFL PLUS - COACHES FILM': {'requirements': {'countryCode': ['US']}}}], 'nfl_plus_plus': [{'NFL PLUS - COACHES FILM': {'requirements': {'countryCode': ['US']}}}]}, 'background': {}, 'cameraSource': 'Sideline', 'clipType': None, 'ctas': [], 'ctaLink': None, 'ctaText': None, 'ctaTarget': None, 'description': '(:03) 16-J.Karty 44 yard field goal is BLOCKED (90-J.Davis), Center-47-A.Ward, Holder-42-E.Evans, RECOVERED by PHI-90-J.Davis at PHI 39. 90-J.Davis for 61 yards, TOUCHDOWN.', 'displayTitle': None, 'startDate': None, 'endDate': None, 'duration': '19', 'episodeNumber': None, 'entitlement': None, 'expirationDate': '2035-09-20T09:04:00.000Z', 'externalId': '-_jkbTiDcXExQwyvNuc4kg', 'fantasyLink': None, 'hostNetwork': None, 'id': None, 'ids': {'awayTeamId': '10402510-8931-0d5f-9815-79bb79649a65', 'gameId': 'f6660056-311e-11f0-b670-ae1250fadad1', 'homeTeamId': '10403700-b939-3cbd-3d16-24d4d6742fa2', 'playId': '4358'}, 'images': [], 'intendedAudience': None, 'introEnd': None, 'mcpPlaybackId': '2318163', 'mobileLink': None, 'mobileTitle': None, 'originalAirDate': '2025-09-21T07:00:00.000Z', 'outroStart': None, 'playIds': ['4358'], 'preRollDisabled': False, 'promoAssets': [], 'promoLink': None, 'promoText': None, 'promoTarget': '_self', 'lastUpdated': None, 'publishDate': '2025-09-22T10:00:00.000Z', 'radioStation': None, 'seriesTitle': None, 'seriesSeason': None, 'series': None, 'slug': None, 'subType': 'Coaches Film Pro', 'summary': None, 'tags': [{'title': 'Davis, Jordan', 'slug': 'davis,-jordan', 'personId': '32004441-5648-7265-ac02-99b487d4f3e4'}, {'title': 'Karty, Joshua', 'slug': 'karty,-joshua', 'personId': '32004b41-5273-7693-d111-9d4c625e76c8'}, {'title': 'Eagles', 'slug': 'eagles', 'teamId': '10403700_b939_3cbd_3d16_24d4d6742fa2'}, {'title': 'Rams', 'slug': 'rams', 'teamId': '10402510_8931_0d5f_9815_79bb79649a65'}, {'gameId': 'f6660056-311e-11f0-b670-ae1250fadad1', 'season': '2025', 'week': '3', 'seasonType': 'REG'}, {'gameId': 'f6660056-311e-11f0-b670-ae1250fadad1', 'season': '2025', 'week': '3', 'seasonType': 'REG'}], 'thumbnail': {'thumbnailUrl': 'https://o300810-mp-lura-live.akamaized.net/1/73/pvw/69B/B29/69BB296C1DCABD6B06A1067504810AF9_2.jpg?hdntl=st=1715000000~exp=2082787200~acl=/*~hmac=7903d9d310da4e4b7d0867e2098dcbb50dfa5d908bf53dd2c392d70447c347e3'}, 'title': 'LA  3-3  PHI 26', 'videos': [], 'webLink': None}, {'type': 'video', 'language': None, 'advertiserId': None, 'author': None, 'authorizations': {'nfl_plus_premium': [{'NFL PLUS - COACHES FILM': {'requirements': {'countryCode': ['US']}}}], 'pro_premium': [{'NFL PLUS - COACHES FILM': {'requirements': {'countryCode': ['US']}}}], 'nfl_plus_plus': [{'NFL PLUS - COACHES FILM': {'requirements': {'countryCode': ['US']}}}]}, 'background': {}, 'cameraSource': 'Broadcast', 'clipType': None, 'ctas': [], 'ctaLink': None, 'ctaText': None, 'ctaTarget': None, 'description': '(:03) 16-J.Karty 44 yard field goal is BLOCKED (90-J.Davis), Center-47-A.Ward, Holder-42-E.Evans, RECOVERED by PHI-90-J.Davis at PHI 39. 90-J.Davis for 61 yards, TOUCHDOWN.', 'displayTitle': None, 'startDate': None, 'endDate': None, 'duration': '19', 'episodeNumber': None, 'entitlement': None, 'expirationDate': '2035-09-20T09:02:56.000Z', 'externalId': 'GO0HGmbQE9fhey3ODzOaYQ', 'fantasyLink': None, 'hostNetwork': None, 'id': None, 'ids': {'awayTeamId': '10402510-8931-0d5f-9815-79bb79649a65', 'gameId': 'f6660056-311e-11f0-b670-ae1250fadad1', 'homeTeamId': '10403700-b939-3cbd-3d16-24d4d6742fa2', 'playId': '4358'}, 'images': [], 'intendedAudience': None, 'introEnd': None, 'mcpPlaybackId': '2318149', 'mobileLink': None, 'mobileTitle': None, 'originalAirDate': '2025-09-21T07:00:00.000Z', 'outroStart': None, 'playIds': ['4358'], 'preRollDisabled': False, 'promoAssets': [], 'promoLink': None, 'promoText': None, 'promoTarget': '_self', 'lastUpdated': None, 'publishDate': '2025-09-22T10:00:00.000Z', 'radioStation': None, 'seriesTitle': None, 'seriesSeason': None, 'series': None, 'slug': None, 'subType': 'Coaches Film', 'summary': None, 'tags': [{'title': 'Davis, Jordan', 'slug': 'davis,-jordan', 'personId': '32004441-5648-7265-ac02-99b487d4f3e4'}, {'title': 'Karty, Joshua', 'slug': 'karty,-joshua', 'personId': '32004b41-5273-7693-d111-9d4c625e76c8'}, {'title': 'Eagles', 'slug': 'eagles', 'teamId': '10403700_b939_3cbd_3d16_24d4d6742fa2'}, {'title': 'Rams', 'slug': 'rams', 'teamId': '10402510_8931_0d5f_9815_79bb79649a65'}, {'gameId': 'f6660056-311e-11f0-b670-ae1250fadad1', 'season': '2025', 'week': '3', 'seasonType': 'REG'}, {'gameId': 'f6660056-311e-11f0-b670-ae1250fadad1', 'season': '2025', 'week': '3', 'seasonType': 'REG'}], 'thumbnail': {'thumbnailUrl': 'https://o300810-mp-lura-live.akamaized.net/1/73/pvw/EFD/A2C/EFDA2CF360694183D89D9845D3B04D08_1.jpg?hdntl=st=1715000000~exp=2082787200~acl=/*~hmac=7903d9d310da4e4b7d0867e2098dcbb50dfa5d908bf53dd2c392d70447c347e3'}, 'title': 'LA  3-3  PHI 26', 'videos': [], 'webLink': None}, {'type': 'video', 'language': None, 'advertiserId': None, 'author': None, 'authorizations': {'nfl_plus_premium': [{'NFL PLUS - COACHES FILM': {'requirements': {'countryCode': ['US']}}}], 'pro_premium': [{'NFL PLUS - COACHES FILM': {'requirements': {'countryCode': ['US']}}}], 'nfl_plus_plus': [{'NFL PLUS - COACHES FILM': {'requirements': {'countryCode': ['US']}}}]}, 'background': {}, 'cameraSource': 'Endzone', 'clipType': None, 'ctas': [], 'ctaLink': None, 'ctaText': None, 'ctaTarget': None, 'description': '(:03) 16-J.Karty 44 yard field goal is BLOCKED (90-J.Davis), Center-47-A.Ward, Holder-42-E.Evans, RECOVERED by PHI-90-J.Davis at PHI 39. 90-J.Davis for 61 yards, TOUCHDOWN.', 'displayTitle': None, 'startDate': None, 'endDate': None, 'duration': '19', 'episodeNumber': None, 'entitlement': None, 'expirationDate': '2035-09-20T09:01:52.000Z', 'externalId': 'S4kNI_bP-oGQunHIEi1u7A', 'fantasyLink': None, 'hostNetwork': None, 'id': None, 'ids': {'awayTeamId': '10402510-8931-0d5f-9815-79bb79649a65', 'gameId': 'f6660056-311e-11f0-b670-ae1250fadad1', 'homeTeamId': '10403700-b939-3cbd-3d16-24d4d6742fa2', 'playId': '4358'}, 'images': [], 'intendedAudience': None, 'introEnd': None, 'mcpPlaybackId': '2318135', 'mobileLink': None, 'mobileTitle': None, 'originalAirDate': '2025-09-21T07:00:00.000Z', 'outroStart': None, 'playIds': ['4358'], 'preRollDisabled': False, 'promoAssets': [], 'promoLink': None, 'promoText': None, 'promoTarget': '_self', 'lastUpdated': None, 'publishDate': '2025-09-22T10:00:00.000Z', 'radioStation': None, 'seriesTitle': None, 'seriesSeason': None, 'series': None, 'slug': None, 'subType': 'Coaches Film Pro', 'summary': None, 'tags': [{'title': 'Davis, Jordan', 'slug': 'davis,-jordan', 'personId': '32004441-5648-7265-ac02-99b487d4f3e4'}, {'title': 'Karty, Joshua', 'slug': 'karty,-joshua', 'personId': '32004b41-5273-7693-d111-9d4c625e76c8'}, {'title': 'Eagles', 'slug': 'eagles', 'teamId': '10403700_b939_3cbd_3d16_24d4d6742fa2'}, {'title': 'Rams', 'slug': 'rams', 'teamId': '10402510_8931_0d5f_9815_79bb79649a65'}, {'gameId': 'f6660056-311e-11f0-b670-ae1250fadad1', 'season': '2025', 'week': '3', 'seasonType': 'REG'}, {'gameId': 'f6660056-311e-11f0-b670-ae1250fadad1', 'season': '2025', 'week': '3', 'seasonType': 'REG'}], 'thumbnail': {'thumbnailUrl': 'https://o300810-mp-lura-live.akamaized.net/1/73/pvw/FA8/C55/FA8C55ABDDE75082977B3B655524D20B_1.jpg?hdntl=st=1715000000~exp=2082787200~acl=/*~hmac=7903d9d310da4e4b7d0867e2098dcbb50dfa5d908bf53dd2c392d70447c347e3'}, 'title': 'LA  3-3  PHI 26', 'videos': [], 'webLink': None}], 'metadata': {'generatedAt': '2025-09-22T14:07:48.045Z'}, 'pagination': {'token': 'eyJhbGciOiJIUzI1NiJ9.eyJsaW1pdCI6MjUsIm9mZnNldCI6MjUsInF1ZXJ5Ijp7ImdhbWVpZCI6ImY2NjYwMDU2LTMxMWUtMTFmMC1iNjcwLWFlMTI1MGZhZGFkMSIsInBsYXlpZCI6IjQzNTgifX0.50CgdIaTJKzvquJiodKu-jQCPCcSvq7kyA6N6M8sz0I'}}

In [21]:
coaches_df = nflpro_api.clean_coaches_data(coaches_data)
coaches_df

,type,camera_source,mcp_playback_id,title,description,duration,external_id,publish_date,sub_type,game_id,away_team_id,home_team_id,play_id,thumbnail_url
0,video,Sideline,2318163,LA 3-3 PHI 26,(:03) 16-J.Karty 44 yard field goal is BLOCKED...,19,-_jkbTiDcXExQwyvNuc4kg,2025-09-22T10:00:00.000Z,Coaches Film Pro,f6660056-311e-11f0-b670-ae1250fadad1,10402510-8931-0d5f-9815-79bb79649a65,10403700-b939-3cbd-3d16-24d4d6742fa2,4358,https://o300810-mp-lura-live.akamaized.net/1/7...
1,video,Broadcast,2318149,LA 3-3 PHI 26,(:03) 16-J.Karty 44 yard field goal is BLOCKED...,19,GO0HGmbQE9fhey3ODzOaYQ,2025-09-22T10:00:00.000Z,Coaches Film,f6660056-311e-11f0-b670-ae1250fadad1,10402510-8931-0d5f-9815-79bb79649a65,10403700-b939-3cbd-3d16-24d4d6742fa2,4358,https://o300810-mp-lura-live.akamaized.net/1/7...
2,video,Endzone,2318135,LA 3-3 PHI 26,(:03) 16-J.Karty 44 yard field goal is BLOCKED...,19,S4kNI_bP-oGQunHIEi1u7A,2025-09-22T10:00:00.000Z,Coaches Film Pro,f6660056-311e-11f0-b670-ae1250fadad1,10402510-8931-0d5f-9815-79bb79649a65,10403700-b939-3cbd-3d16-24d4d6742fa2,4358,https://o300810-mp-lura-live.akamaized.net/1/7...

In [22]:
game_id_elias[6]

'2025092105'

## Coaches Film

In [23]:
nflpro.download_play_film(
    coaches_df=coaches_df,
    game_id_elias=game_id_elias[6],
    play_id=p,
)

Sideline: 2318163
https://api.nfl.com/play/v1/asset/2318163
Request URL: https://api.nfl.com/play/v1/asset/2318163
Request Headers: {'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJjbGllbnRJZCI6ImU1MzVjN2MwLTgxN2YtNDc3Ni04OTkwLTU2NTU2ZjhiMTkyOCIsImNsaWVudEtleSI6IjRjRlVXNkRtd0pwelQ5TDdMckczcVJBY0FCRzVzMDRnIiwiZGV2aWNlSWQiOiJlODQxNzkzYi00YTY3LTRjYzEtOGJjNi1kOWZjMDgxMDIwZDAiLCJpc3MiOiJORkwiLCJwbGFucyI6W3sicGxhbiI6ImZyZWUiLCJleHBpcmF0aW9uRGF0ZSI6IjIwMjYtMDktMjIiLCJzb3VyY2UiOiJORkwiLCJzdGFydERhdGUiOiIyMDI1LTA5LTIyIiwic3RhdHVzIjoiQUNUSVZFIiwidHJpYWwiOmZhbHNlfSx7InBsYW4iOiJORkxfUExVU19QUkVNSVVNIiwiYmlsbGluZ1R5cGUiOiJhbm51YWwiLCJleHBpcmF0aW9uRGF0ZSI6IjIwMjYtMDktMDQiLCJleHRlcm5hbFN1YnNjcmlwdGlvbklkIjoieGpkMDNmeHBoOGtjIiwic291cmNlIjoiV0VCIiwic3RhcnREYXRlIjoiMjAyNS0wOS0wNCIsInN0YXR1cyI6IkFDVElWRSIsInRyaWFsIjpmYWxzZX1dLCJEaXNwbGF5TmFtZSI6IldFQl9ERVNLVE9QX0RFU0tUT1AiLCJOb3RlcyI6IiIsImZvcm1GYWN0b3IiOiJERVNLVE9QIiwibHVyYUFwcEtleSI6IlNaczU3ZEJHUnhiTDcyOGxWcDdEWVEiLCJwbGF0Zm9ybSI6IkRFU0tUT1AiLCJwcm9kdWN0TmFtZSI6IldFQiIsInJvbGVzIjpbImNvbnRlbnQiLCJleHBlcmllbmNlIiwiZm9vdGJhbGwiLCJ1dGlsaXRpZXMiLCJ0ZWFtcyIsInBsYXkiLCJsaXZlIiwiaWRlbnRpdHkiLCJuZ3Nfc3RhdHMiLCJwYXltZW50c19hcGkiLCJuZ3NfdHJhY2tpbmciLCJuZ3NfcGxhdGZvcm0iLCJuZ3NfY29udGVudCIsIm5nc19jb21iaW5lIiwibmdzX2FkdmFuY2VkX3N0YXRzIiwibmZsX3BybyIsImVjb21tIiwibmZsX2lkX2FwaSIsInV0aWxpdGllc19sb2NhdGlvbiIsImlkZW50aXR5X29pZGMiLCJuZ3Nfc3NlIiwiYWNjb3VudHMiLCJjb25zZW50cyIsInN1Yl9wYXJ0bmVyc2hpcHMiLCJjb25jdXJyZW5jeSIsImtleXN0b3JlIiwiZnJlZSIsIk5GTF9QTFVTX1BSRU1JVU0iXSwibmV0d29ya1R5cGUiOiJvdGhlciIsImNpdHkiOiJwaGlsYWRlbHBoaWEiLCJjb3VudHJ5Q29kZSI6IlVTIiwiZG1hQ29kZSI6IjUwNCIsImhtYVRlYW1zIjpbIjEwNDAzNzAwLWI5MzktM2NiZC0zZDE2LTI0ZDRkNjc0MmZhMiJdLCJyZWdpb24iOiJQQSIsInppcENvZGUiOiIxOTE0NiIsImJyb3dzZXIiOiJPdGhlciIsImNlbGx1bGFyIjpmYWxzZSwiZW52aXJvbm1lbnQiOiJwcm9kdWN0aW9uIiwidWlkIjoiMDk1OTBjZDcxMDRkMzE2ZTQ5ZmZkMjk0NGYxMTM5YzUiLCJleHAiOjE3NTg1NTM2Nzl9.qbtbfJbk_ibEHuP_LyrvwUO-J7ql0-boM0PwmiTq_14', 'Accept': 'application/json, text/plain, */*'}
Request Params: {}
Playlist saved to ../playlists/2025092105-4358.m3u8
['#EXTM3U', '#EXT-X-INDEPENDENT-SEGMENTS', '#EXT-X-STREAM-INF:BANDWIDTH=953900,FRAME-RATE=60,RESOLUTION=1920x1080,AVERAGE-BANDWIDTH=878000,CODECS="avc1.4d002a"', 'https://dcs-vod.mp.lura.live/vod/p/953900/prog.m3u8?i=i176963772-n9ab51046-17c5-40ab-9ba3-2bee0a7d9e0e', '#EXT-X-STREAM-INF:BANDWIDTH=1741400,FRAME-RATE=60,RESOLUTION=1920x1080,AVERAGE-BANDWIDTH=1628000,CODECS="avc1.4d002a"', 'https://dcs-vod.mp.lura.live/vod/p/1741400/prog.m3u8?i=i176963772-n9ab51046-17c5-40ab-9ba3-2bee0a7d9e0e', '#EXT-X-STREAM-INF:BANDWIDTH=3316400,FRAME-RATE=60,RESOLUTION=1920x1080,AVERAGE-BANDWIDTH=3128000,CODECS="avc1.4d002a"', 'https://dcs-vod.mp.lura.live/vod/p/3316400/prog.m3u8?i=i176963772-n9ab51046-17c5-40ab-9ba3-2bee0a7d9e0e', '#EXT-X-STREAM-INF:BANDWIDTH=5416400,FRAME-RATE=60,RESOLUTION=1920x1080,AVERAGE-BANDWIDTH=5128000,CODECS="avc1.4d002a"', 'https://dcs-vod.mp.lura.live/vod/p/5416400/prog.m3u8?i=i176963772-n9ab51046-17c5-40ab-9ba3-2bee0a7d9e0e', '#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=878000,RESOLUTION=1920x1080,CODECS="avc1.4d002a",URI="https://dcs-vod.mp.lura.live/vod/p/878000/iframes.m3u8?i=i176963772-n9ab51046-17c5-40ab-9ba3-2bee0a7d9e0e"', '#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=1628000,RESOLUTION=1920x1080,CODECS="avc1.4d002a",URI="https://dcs-vod.mp.lura.live/vod/p/1628000/iframes.m3u8?i=i176963772-n9ab51046-17c5-40ab-9ba3-2bee0a7d9e0e"', '#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=3128000,RESOLUTION=1920x1080,CODECS="avc1.4d002a",URI="https://dcs-vod.mp.lura.live/vod/p/3128000/iframes.m3u8?i=i176963772-n9ab51046-17c5-40ab-9ba3-2bee0a7d9e0e"', '#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=5128000,RESOLUTION=1920x1080,CODECS="avc1.4d002a",URI="https://dcs-vod.mp.lura.live/vod/p/5128000/iframes.m3u8?i=i176963772-n9ab51046-17c5-40ab-9ba3-2bee0a7d9e0e"', '#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=7828000,RESOLUTION=1920x1080,CODECS="avc1.4d002a",URI="https://dcs-vod.mp.lura.live/vod/p/7828000/iframes.m3u8?i=i176963772-n9ab51046-17c5-40ab-9ba3-2bee0a7d9e0e"']
Successfully downloaded https://dcs-vod.mp.lura.live/vod/p/master.m3u8?encp=koAmy-uE-u0Cx0gAnbzDTw:_TlraegdryJDeXSz6qen2IPAu_FAHTVRS142sqGBL1Z_JPgL5NO5KmBvQQRP3zlJZUu71nt0XIB7kzBF89c69CnpPbaJo6koZ_d4RjMHe1IOjwg3OnAc-xwAf1qXMKKt23XHdbE8-Ea2Q3paICes896vcZOGUvxZ-neYggpCmddyHaK0tNvR5aO2MIIsnyd-Z5ZDi_1whsSWjIaT5mUb3O8z9GKdQlye5QWeTUZCt7c3xwexrMihgG_7Lc8I9QtrLnGuThsaKv8oLHnwdFCu8e7YUJgp_XtMMCVsNchGTuLc030Tm9VdlHcIEZZQk9yP3dKZMyHQ3BWvdGIPelDvpXrvu_BZ5_Sw35eClwlqmIcT-mmp1yyq65ZFmpX6uGvAkLdL3mQMd2WYyn1IH-zbt4UQe6B0Zp6OhLKVVQiuISv-DplAnl9l8IsM5XipzEzjba5O7EliV2FhfJXsEedmICYdgRSCMHwUcKJkPp_xAiPi_jiZsfrxZKohjmQSz-9E2lLQPVa8D5oH04xPCpiFso4Izt08mZgPp8ya001cuqnsrDHeebUMqAzvwxRLTR1IWb5fKj5pNGyveqMLWz-onuxfMHaaDute_CnprW-USqZtb-D1HEtLnakXCWuPf_LR_svS1pppzYzYkGtgkTDchv_Pthu6Sq8u9DNP4LQnuCWpdoct94tbqWa6RQI1mp943b-PqZMkeWAGAs1R_Q5VL4HgaddHyleju9d8SZsSGum5GPRd7RDm4178Y67l9MOR5kWa5ZiS85AjMKFVgF-shEEluZ9hnBgemo3vUbAEVzGpbMckQn2LC3Yz9ZzucAVL_ZTsZADRD_Ikq_ha1TK9S9TtYoZESSBOx3H9Qsi7KpRdBNC9YKz6bXzP9H_TymbLcG-cJCISa2p1p9w-IAvnSZ8yinGX57uuIsjX8DQs3KubyVYFaLMrjDGxIuNNChSPdQWw1cNvP_KIeVXqTYxoHPZx4OZKBu3fW1c1Feh2skqrK_H-QyG_5sbgtIEnbx0szPeunns4pKoPCNrV9RGknaGt0MFPt_FiYYOw_j5qxi_ejU73Cvd6OUUgKElX3ODVtoR60YUTmQQNj8WONSd95l1gijXHprwrZkqcgZoX7PwViVSxvG5YgZG7dxpM6geaKHk1y_Vg_ChCYfPNroo5B_WN_dQgIiaIgPOXc7y_F0DmkVWcQP4cuIhOo9KhtHpV2BeGrfdxgxu2sH5WcvNOJADWouGdD8JYtTlL7TMItsQMV-y291szqbhATtebqpFJdOPwpXngNdVSqhHO6tvjyA-0NraMEF1Ks2UvtwW9SPTih1n8FsPn5ndNuSoBtYeUStyqwJKefW9JEsbVLxCaiScNJYf1LMvu6XRbsUf9zCd6y4HflQhEqxMrayl-6VnDhktHVg_AYQq2XBrkvySrWoRWZawUo45HGgpOoTsZTWyIxdgS-ty7pYLurUFVHm_Pk-smibMpLUJOIm3lPtmeoBmi-jA6OWJu7mbeSZ7r_4GruK0QkXMy9uAmew_r5pCr&anvauth=tb=0~te=1758550980~sgn=92d9bf99ecf3907a0f34cd9b71982a6ee7de7b05961fac42fa66c3adf2348238&t=1758550080 to ../film/2025092105-4358-2318163-Sideline.mp4
Broadcast: 2318149
https://api.nfl.com/play/v1/asset/2318149
Request URL: https://api.nfl.com/play/v1/asset/2318149
Request Headers: {'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJjbGllbnRJZCI6ImU1MzVjN2MwLTgxN2YtNDc3Ni04OTkwLTU2NTU2ZjhiMTkyOCIsImNsaWVudEtleSI6IjRjRlVXNkRtd0pwelQ5TDdMckczcVJBY0FCRzVzMDRnIiwiZGV2aWNlSWQiOiJlODQxNzkzYi00YTY3LTRjYzEtOGJjNi1kOWZjMDgxMDIwZDAiLCJpc3MiOiJORkwiLCJwbGFucyI6W3sicGxhbiI6ImZyZWUiLCJleHBpcmF0aW9uRGF0ZSI6IjIwMjYtMDktMjIiLCJzb3VyY2UiOiJORkwiLCJzdGFydERhdGUiOiIyMDI1LTA5LTIyIiwic3RhdHVzIjoiQUNUSVZFIiwidHJpYWwiOmZhbHNlfSx7InBsYW4iOiJORkxfUExVU19QUkVNSVVNIiwiYmlsbGluZ1R5cGUiOiJhbm51YWwiLCJleHBpcmF0aW9uRGF0ZSI6IjIwMjYtMDktMDQiLCJleHRlcm5hbFN1YnNjcmlwdGlvbklkIjoieGpkMDNmeHBoOGtjIiwic291cmNlIjoiV0VCIiwic3RhcnREYXRlIjoiMjAyNS0wOS0wNCIsInN0YXR1cyI6IkFDVElWRSIsInRyaWFsIjpmYWxzZX1dLCJEaXNwbGF5TmFtZSI6IldFQl9ERVNLVE9QX0RFU0tUT1AiLCJOb3RlcyI6IiIsImZvcm1GYWN0b3IiOiJERVNLVE9QIiwibHVyYUFwcEtleSI6IlNaczU3ZEJHUnhiTDcyOGxWcDdEWVEiLCJwbGF0Zm9ybSI6IkRFU0tUT1AiLCJwcm9kdWN0TmFtZSI6IldFQiIsInJvbGVzIjpbImNvbnRlbnQiLCJleHBlcmllbmNlIiwiZm9vdGJhbGwiLCJ1dGlsaXRpZXMiLCJ0ZWFtcyIsInBsYXkiLCJsaXZlIiwiaWRlbnRpdHkiLCJuZ3Nfc3RhdHMiLCJwYXltZW50c19hcGkiLCJuZ3NfdHJhY2tpbmciLCJuZ3NfcGxhdGZvcm0iLCJuZ3NfY29udGVudCIsIm5nc19jb21iaW5lIiwibmdzX2FkdmFuY2VkX3N0YXRzIiwibmZsX3BybyIsImVjb21tIiwibmZsX2lkX2FwaSIsInV0aWxpdGllc19sb2NhdGlvbiIsImlkZW50aXR5X29pZGMiLCJuZ3Nfc3NlIiwiYWNjb3VudHMiLCJjb25zZW50cyIsInN1Yl9wYXJ0bmVyc2hpcHMiLCJjb25jdXJyZW5jeSIsImtleXN0b3JlIiwiZnJlZSIsIk5GTF9QTFVTX1BSRU1JVU0iXSwibmV0d29ya1R5cGUiOiJvdGhlciIsImNpdHkiOiJwaGlsYWRlbHBoaWEiLCJjb3VudHJ5Q29kZSI6IlVTIiwiZG1hQ29kZSI6IjUwNCIsImhtYVRlYW1zIjpbIjEwNDAzNzAwLWI5MzktM2NiZC0zZDE2LTI0ZDRkNjc0MmZhMiJdLCJyZWdpb24iOiJQQSIsInppcENvZGUiOiIxOTE0NiIsImJyb3dzZXIiOiJPdGhlciIsImNlbGx1bGFyIjpmYWxzZSwiZW52aXJvbm1lbnQiOiJwcm9kdWN0aW9uIiwidWlkIjoiMDk1OTBjZDcxMDRkMzE2ZTQ5ZmZkMjk0NGYxMTM5YzUiLCJleHAiOjE3NTg1NTM2ODN9.5n_pnCirRutNlnc_9X9WB37JNtrjjPFm4I-ZMu3lr08', 'Accept': 'application/json, text/plain, */*'}
Request Params: {}
Playlist saved to ../playlists/2025092105-4358.m3u8
['#EXTM3U', '#EXT-X-INDEPENDENT-SEGMENTS', '#EXT-X-STREAM-INF:BANDWIDTH=355400,FRAME-RATE=60,RESOLUTION=416x234,AVERAGE-BANDWIDTH=308000,CODECS="avc1.42001e, mp4a.40.2"', 'https://dcs-vod.mp.lura.live/vod/p/355400/prog.m3u8?i=i176955630-nc56326cc-f0fd-40a4-84c2-402989852fbc', '#EXT-X-STREAM-INF:BANDWIDTH=502400,FRAME-RATE=60,RESOLUTION=416x234,AVERAGE-BANDWIDTH=448000,CODECS="avc1.42001e, mp4a.40.2"', 'https://dcs-vod.mp.lura.live/vod/p/502400/prog.m3u8?i=i176955630-nc56326cc-f0fd-40a4-84c2-402989852fbc', '#EXT-X-STREAM-INF:BANDWIDTH=691400,FRAME-RATE=60,RESOLUTION=640x360,AVERAGE-BANDWIDTH=628000,CODECS="avc1.42001f, mp4a.40.2"', 'https://dcs-vod.mp.lura.live/vod/p/691400/prog.m3u8?i=i176955630-nc56326cc-f0fd-40a4-84c2-402989852fbc', '#EXT-X-STREAM-INF:BANDWIDTH=1006400,FRAME-RATE=60,RESOLUTION=640x360,AVERAGE-BANDWIDTH=928000,CODECS="avc1.4d001f, mp4a.40.2"', 'https://dcs-vod.mp.lura.live/vod/p/1006400/prog.m3u8?i=i176955630-nc56326cc-f0fd-40a4-84c2-402989852fbc', '#EXT-X-STREAM-INF:BANDWIDTH=1426400,FRAME-RATE=60,RESOLUTION=768x432,AVERAGE-BANDWIDTH=1328000,CODECS="avc1.4d001f, mp4a.40.2"', 'https://dcs-vod.mp.lura.live/vod/p/1426400/prog.m3u8?i=i176955630-nc56326cc-f0fd-40a4-84c2-402989852fbc', '#EXT-X-STREAM-INF:BANDWIDTH=2266400,FRAME-RATE=60,RESOLUTION=768x432,AVERAGE-BANDWIDTH=2128000,CODECS="avc1.4d001f, mp4a.40.2"', 'https://dcs-vod.mp.lura.live/vod/p/2266400/prog.m3u8?i=i176955630-nc56326cc-f0fd-40a4-84c2-402989852fbc', '#EXT-X-STREAM-INF:BANDWIDTH=3526400,FRAME-RATE=60,RESOLUTION=1280x720,AVERAGE-BANDWIDTH=3328000,CODECS="avc1.4d0020, mp4a.40.2"', 'https://dcs-vod.mp.lura.live/vod/p/3526400/prog.m3u8?i=i176955630-nc56326cc-f0fd-40a4-84c2-402989852fbc', '#EXT-X-STREAM-INF:BANDWIDTH=5416400,FRAME-RATE=60,RESOLUTION=1280x720,AVERAGE-BANDWIDTH=5128000,CODECS="avc1.4d0020, mp4a.40.2"', 'https://dcs-vod.mp.lura.live/vod/p/5416400/prog.m3u8?i=i176955630-nc56326cc-f0fd-40a4-84c2-402989852fbc', '#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=308000,RESOLUTION=416x234,CODECS="avc1.42001e",URI="https://dcs-vod.mp.lura.live/vod/p/308000/iframes.m3u8?i=i176955630-nc56326cc-f0fd-40a4-84c2-402989852fbc"', '#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=448000,RESOLUTION=416x234,CODECS="avc1.42001e",URI="https://dcs-vod.mp.lura.live/vod/p/448000/iframes.m3u8?i=i176955630-nc56326cc-f0fd-40a4-84c2-402989852fbc"', '#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=628000,RESOLUTION=640x360,CODECS="avc1.42001f",URI="https://dcs-vod.mp.lura.live/vod/p/628000/iframes.m3u8?i=i176955630-nc56326cc-f0fd-40a4-84c2-402989852fbc"', '#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=928000,RESOLUTION=640x360,CODECS="avc1.4d001f",URI="https://dcs-vod.mp.lura.live/vod/p/928000/iframes.m3u8?i=i176955630-nc56326cc-f0fd-40a4-84c2-402989852fbc"', '#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=1328000,RESOLUTION=768x432,CODECS="avc1.4d001f",URI="https://dcs-vod.mp.lura.live/vod/p/1328000/iframes.m3u8?i=i176955630-nc56326cc-f0fd-40a4-84c2-402989852fbc"', '#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=2128000,RESOLUTION=768x432,CODECS="avc1.4d001f",URI="https://dcs-vod.mp.lura.live/vod/p/2128000/iframes.m3u8?i=i176955630-nc56326cc-f0fd-40a4-84c2-402989852fbc"', '#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=3328000,RESOLUTION=1280x720,CODECS="avc1.4d0020",URI="https://dcs-vod.mp.lura.live/vod/p/3328000/iframes.m3u8?i=i176955630-nc56326cc-f0fd-40a4-84c2-402989852fbc"', '#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=5128000,RESOLUTION=1280x720,CODECS="avc1.4d0020",URI="https://dcs-vod.mp.lura.live/vod/p/5128000/iframes.m3u8?i=i176955630-nc56326cc-f0fd-40a4-84c2-402989852fbc"', '#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=8128000,RESOLUTION=1920x1080,CODECS="avc1.4d002a",URI="https://dcs-vod.mp.lura.live/vod/p/8128000/iframes.m3u8?i=i176955630-nc56326cc-f0fd-40a4-84c2-402989852fbc"', '#EXT-X-IMAGE-STREAM-INF:BANDWIDTH=308000,RESOLUTION=416x234,CODECS="jpeg",URI="https://dcs-vod.mp.lura.live/vod/p/308000/images.m3u8?i=i176955630-nc56326cc-f0fd-40a4-84c2-402989852fbc"', '#EXT-X-IMAGE-STREAM-INF:BANDWIDTH=448000,RESOLUTION=416x234,CODECS="jpeg",URI="https://dcs-vod.mp.lura.live/vod/p/448000/images.m3u8?i=i176955630-nc56326cc-f0fd-40a4-84c2-402989852fbc"', '#EXT-X-IMAGE-STREAM-INF:BANDWIDTH=628000,RESOLUTION=640x360,CODECS="jpeg",URI="https://dcs-vod.mp.lura.live/vod/p/628000/images.m3u8?i=i176955630-nc56326cc-f0fd-40a4-84c2-402989852fbc"', '#EXT-X-IMAGE-STREAM-INF:BANDWIDTH=928000,RESOLUTION=640x360,CODECS="jpeg",URI="https://dcs-vod.mp.lura.live/vod/p/928000/images.m3u8?i=i176955630-nc56326cc-f0fd-40a4-84c2-402989852fbc"', '#EXT-X-IMAGE-STREAM-INF:BANDWIDTH=1328000,RESOLUTION=768x432,CODECS="jpeg",URI="https://dcs-vod.mp.lura.live/vod/p/1328000/images.m3u8?i=i176955630-nc56326cc-f0fd-40a4-84c2-402989852fbc"', '#EXT-X-IMAGE-STREAM-INF:BANDWIDTH=2128000,RESOLUTION=768x432,CODECS="jpeg",URI="https://dcs-vod.mp.lura.live/vod/p/2128000/images.m3u8?i=i176955630-nc56326cc-f0fd-40a4-84c2-402989852fbc"']
Successfully downloaded https://dcs-vod.mp.lura.live/vod/p/master.m3u8?encp=NEhoiwYRob5TlH41JcDYKg:pgoQ_TwNG9OplUD1_4CHscMEOz0CoZmDPaU3Pxmf9Z14VQTE6vwEf0zAt5kk-txigGYjbynUmaiQKi-5U8uvNsT8K8qWzjcEaXoEtEzV9TqMLDmS2h2uzfwOuKxUCYgVAg-UzL3AUVKa4HLIHJlT8iJmDylhzSMclpRd8CMmoq6ZkERgBs4Psr5R1lLVDsG4kc7JEdCU0W7rLSZP0iFzDmp9_9QRfAyEXUXxhy8DR3pfXyKjkglDwHbFiOY-CdI9OOvYpMzdmEGO5FJ8DverQw7GBgCZ8wJ6Xz-HMxDkQ4pSkIcv0Quk-BVP31No3SueoLtzwgmfnaTCbR2tWDBK-UM_pTh_3-EjbexrbGjlQ2bAnuCiZrmxJGwvStb9k1nT-__2fL-W9EEsoO3USpYeMmpo9_qPCW0EMrWLb6GsD08abi6RhAcjAaBUAKhukDyIKOMV7_l8h6zlaE1CawqiD7zknW7edxk5J4HRjkHDO7hFa2f3p7tuv_Sa7bOTIj_B9MWhctlGI2HxE3OfwnDQGcQrvHreneluZW4TFyczl4Vj9BkwTJX6eIJWo9jFwYbwcK4BmXBUnRTJWhlDZ9D7ZTbFaPxbKKpWuxdjQLMrRx9JWBBM2lnA0LkIX32bI3bLoY3NWodY8M2v_VFHoc-7CtGmmWqt1Z3u6Ly8HlMYcQ1RpajXYsPu6mLzmaOFhUhfZQwmC2VAFuz6EqAQubQCamrDtx75zV2YMWXISbcFSvu5ZdqXIfDry3E5BHvbUfKusiK-U-3YjNLF6dCqQIl68Og_eQj6sHQlEgty9IvQ1eN72v3keasGl_V9DA_uhRuUtxaNTFR61se1Q4X_zIrqHgxXOWgDbKQJm3fYvH9smh_RV-bjRyvW4l_d8PCiJNVkvLf7BrPuWyda3l1XI-v8kqs1Z-quFeLQ--pBG-MLcgjRY0DbijyAJifOf0j2zgaWJjFeOXHGBhDuI-ivjApez2DzW2KNe2INUKT75ReCMxVX2ukQPfURjcoiQ0jAgGrRh-ShvyITbUXUiUFbfOMSFOp6dAalDxCzGA-R2lM0z3b5pRKInqbNOzxCfsYnCMbNMnRxh1DLIwWcElK3EGLtjxoO3oqxeTeuTPxuRLi_pK4Lw4ACNe0RQtyORbqjcl1tvrsfoyJ-iKVS6m3Z0jd4ILycsRZcUCbDDQ1cpqJnluuEZwqkdbAhVl6fv2RxDkaxbSOvXqVBzEZ2td-cQrR5apMqjQiLSUCL2dq0LTpxi7CVuvq32zNROi10lHOU1PCZ-pCpr9g24zhIRjfkzNkH6U_QdXpS32P2BfWQ7pwF_Eu3KIC3yucrhToTqsuPmonaDvrpvxd_5iZNsxKrVWvwdg7Vn3h00T2seNODBOko_tHZUmn7M-8uWwtd87JObcxZYBKLfK8WyIaQXD9REec4waW0_nxnYya9cwpwxYIy0GdfVIOQfeTk7OJGXwbhtuQufxM03ZJSeF3XCsjrZlK8ZFY2B8boHmZAZ0zTfiaJNqNMTKNc3EHwEMs4MqMRdxdj&anvauth=tb=0~te=1758550984~sgn=68aff7db1b3cf6c752de854b62dfdf747c400480d13bf46cb78f52abdc9edc6a&t=1758550084 to ../film/2025092105-4358-2318149-Broadcast.mp4
Endzone: 2318135
https://api.nfl.com/play/v1/asset/2318135
Request URL: https://api.nfl.com/play/v1/asset/2318135
Request Headers: {'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJjbGllbnRJZCI6ImU1MzVjN2MwLTgxN2YtNDc3Ni04OTkwLTU2NTU2ZjhiMTkyOCIsImNsaWVudEtleSI6IjRjRlVXNkRtd0pwelQ5TDdMckczcVJBY0FCRzVzMDRnIiwiZGV2aWNlSWQiOiJlODQxNzkzYi00YTY3LTRjYzEtOGJjNi1kOWZjMDgxMDIwZDAiLCJpc3MiOiJORkwiLCJwbGFucyI6W3sicGxhbiI6ImZyZWUiLCJleHBpcmF0aW9uRGF0ZSI6IjIwMjYtMDktMjIiLCJzb3VyY2UiOiJORkwiLCJzdGFydERhdGUiOiIyMDI1LTA5LTIyIiwic3RhdHVzIjoiQUNUSVZFIiwidHJpYWwiOmZhbHNlfSx7InBsYW4iOiJORkxfUExVU19QUkVNSVVNIiwiYmlsbGluZ1R5cGUiOiJhbm51YWwiLCJleHBpcmF0aW9uRGF0ZSI6IjIwMjYtMDktMDQiLCJleHRlcm5hbFN1YnNjcmlwdGlvbklkIjoieGpkMDNmeHBoOGtjIiwic291cmNlIjoiV0VCIiwic3RhcnREYXRlIjoiMjAyNS0wOS0wNCIsInN0YXR1cyI6IkFDVElWRSIsInRyaWFsIjpmYWxzZX1dLCJEaXNwbGF5TmFtZSI6IldFQl9ERVNLVE9QX0RFU0tUT1AiLCJOb3RlcyI6IiIsImZvcm1GYWN0b3IiOiJERVNLVE9QIiwibHVyYUFwcEtleSI6IlNaczU3ZEJHUnhiTDcyOGxWcDdEWVEiLCJwbGF0Zm9ybSI6IkRFU0tUT1AiLCJwcm9kdWN0TmFtZSI6IldFQiIsInJvbGVzIjpbImNvbnRlbnQiLCJleHBlcmllbmNlIiwiZm9vdGJhbGwiLCJ1dGlsaXRpZXMiLCJ0ZWFtcyIsInBsYXkiLCJsaXZlIiwiaWRlbnRpdHkiLCJuZ3Nfc3RhdHMiLCJwYXltZW50c19hcGkiLCJuZ3NfdHJhY2tpbmciLCJuZ3NfcGxhdGZvcm0iLCJuZ3NfY29udGVudCIsIm5nc19jb21iaW5lIiwibmdzX2FkdmFuY2VkX3N0YXRzIiwibmZsX3BybyIsImVjb21tIiwibmZsX2lkX2FwaSIsInV0aWxpdGllc19sb2NhdGlvbiIsImlkZW50aXR5X29pZGMiLCJuZ3Nfc3NlIiwiYWNjb3VudHMiLCJjb25zZW50cyIsInN1Yl9wYXJ0bmVyc2hpcHMiLCJjb25jdXJyZW5jeSIsImtleXN0b3JlIiwiZnJlZSIsIk5GTF9QTFVTX1BSRU1JVU0iXSwibmV0d29ya1R5cGUiOiJvdGhlciIsImNpdHkiOiJwaGlsYWRlbHBoaWEiLCJjb3VudHJ5Q29kZSI6IlVTIiwiZG1hQ29kZSI6IjUwNCIsImhtYVRlYW1zIjpbIjEwNDAzNzAwLWI5MzktM2NiZC0zZDE2LTI0ZDRkNjc0MmZhMiJdLCJyZWdpb24iOiJQQSIsInppcENvZGUiOiIxOTE0NiIsImJyb3dzZXIiOiJPdGhlciIsImNlbGx1bGFyIjpmYWxzZSwiZW52aXJvbm1lbnQiOiJwcm9kdWN0aW9uIiwidWlkIjoiMDk1OTBjZDcxMDRkMzE2ZTQ5ZmZkMjk0NGYxMTM5YzUiLCJleHAiOjE3NTg1NTM2ODd9.MMN_xiD3iKq_s0Q2cm6G6p-4IhjgI9kISPCGzI5YCYU', 'Accept': 'application/json, text/plain, */*'}
Request Params: {}
Playlist saved to ../playlists/2025092105-4358.m3u8
['#EXTM3U', '#EXT-X-INDEPENDENT-SEGMENTS', '#EXT-X-STREAM-INF:BANDWIDTH=953900,FRAME-RATE=60,RESOLUTION=1920x1080,AVERAGE-BANDWIDTH=878000,CODECS="avc1.4d002a"', 'https://dcs-vod.mp.lura.live/vod/p/953900/prog.m3u8?i=i176963706-ndd56f4d8-1806-40cd-ad73-b64878874f60', '#EXT-X-STREAM-INF:BANDWIDTH=1741400,FRAME-RATE=60,RESOLUTION=1920x1080,AVERAGE-BANDWIDTH=1628000,CODECS="avc1.4d002a"', 'https://dcs-vod.mp.lura.live/vod/p/1741400/prog.m3u8?i=i176963706-ndd56f4d8-1806-40cd-ad73-b64878874f60', '#EXT-X-STREAM-INF:BANDWIDTH=3316400,FRAME-RATE=60,RESOLUTION=1920x1080,AVERAGE-BANDWIDTH=3128000,CODECS="avc1.4d002a"', 'https://dcs-vod.mp.lura.live/vod/p/3316400/prog.m3u8?i=i176963706-ndd56f4d8-1806-40cd-ad73-b64878874f60', '#EXT-X-STREAM-INF:BANDWIDTH=5416400,FRAME-RATE=60,RESOLUTION=1920x1080,AVERAGE-BANDWIDTH=5128000,CODECS="avc1.4d002a"', 'https://dcs-vod.mp.lura.live/vod/p/5416400/prog.m3u8?i=i176963706-ndd56f4d8-1806-40cd-ad73-b64878874f60', '#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=878000,RESOLUTION=1920x1080,CODECS="avc1.4d002a",URI="https://dcs-vod.mp.lura.live/vod/p/878000/iframes.m3u8?i=i176963706-ndd56f4d8-1806-40cd-ad73-b64878874f60"', '#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=1628000,RESOLUTION=1920x1080,CODECS="avc1.4d002a",URI="https://dcs-vod.mp.lura.live/vod/p/1628000/iframes.m3u8?i=i176963706-ndd56f4d8-1806-40cd-ad73-b64878874f60"', '#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=3128000,RESOLUTION=1920x1080,CODECS="avc1.4d002a",URI="https://dcs-vod.mp.lura.live/vod/p/3128000/iframes.m3u8?i=i176963706-ndd56f4d8-1806-40cd-ad73-b64878874f60"', '#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=5128000,RESOLUTION=1920x1080,CODECS="avc1.4d002a",URI="https://dcs-vod.mp.lura.live/vod/p/5128000/iframes.m3u8?i=i176963706-ndd56f4d8-1806-40cd-ad73-b64878874f60"', '#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=7828000,RESOLUTION=1920x1080,CODECS="avc1.4d002a",URI="https://dcs-vod.mp.lura.live/vod/p/7828000/iframes.m3u8?i=i176963706-ndd56f4d8-1806-40cd-ad73-b64878874f60"']

## Next-Gen Stats

In [17]:
season_insights_offseason = nflpro_api.get_season_insights(
        limit=100,
        season=2025,
        tags=["nfl-pro", "offseason",],
        headers={
                "Referer":"https://pro.nfl.com/insights",
        },
)

if season_insights_offseason:
        print("Season Insights Offseason:")
        print(season_insights_offseason)

# nflpro_api.stats_to_dataframe(season_insights_offseason)

Season Insights Offseason:

In [18]:
season_insights_pregame = nflpro_api.get_season_insights(
        limit=100,
        season=2025,
        tags=["nfl-pro", "next-gen-stats", "pregame",],
        headers={
                "Referer":"https://pro.nfl.com/insights",
        },
)

if season_insights_pregame:
        print("Season Insights Pregame:")
        print(season_insights_pregame)

# nflpro_api.stats_to_dataframe(season_insights_pregame)

Season Insights Pregame:

In [19]:
season_insights_postgame = nflpro_api.get_season_insights(
        limit=100,
        season=2025,
        tags=["nfl-pro", "next-gen-stats", "postgame",],
        headers={
                "Referer":"https://pro.nfl.com/insights",
        }
)

if season_insights_postgame:
        print("Season Insights Postgame:")
        print(season_insights_postgame)

# nflpro_api.stats_to_dataframe(season_insights_postgame)

Season Insights Postgame:

In [20]:
season_insights_editorial = nflpro_api.get_season_insights(
        limit=100,
        season=2025,
        tags=["nfl-pro", "editorial",],
        headers={
                "Referer":"https://pro.nfl.com/insights",
        },
        # print_url=True
)

if season_insights_editorial:
        print("Season Insights Editorial:")
        print(season_insights_editorial)

# nflpro_api.stats_to_dataframe(season_insights_editorial)

Season Insights Editorial: